color: true

core config:
    dbuser: wordpress
    dbpass: wordpress
    extra-php: |
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_AUTO_UPDATE_CORE', false );
        define( 'WP_HOME', 'http://'. $_SERVER['SERVER_NAME'] );
        define( 'WP_SITEURL', 'http://'. $_SERVER['SERVER_NAME'] );
        define( 'SAVEQUERIES', true );
