stages:
  - lint
  - build
  - test

default:
  image: node:latest
  script:
    - npm ci
  cache:
    paths: [node_modules/]

lint:styles:
  stage: lint
  only:
    - merge_requests
  script:
    - npm run lint:styles
