title: Craig (is) Wayne
author: Craig Wayne
contact:
  mobile: +27716865307
  email: craigiswayne@gmail.com
logo: /assets/images/avatar-compressed.png
description: >- # this means to ignore newlines until "baseurl:"
  A little github pages experiment
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-130131269-1
social:
  twitter:
    username: craigiswayne
  github:
    username: craigiswayne
  gitlab:
    username: craigiswayne
  codepen:
    username: craigiswayne
  linkedin:
    username: craigiswayne
  stackoverflow:
    userID: 1654250
  wakatime:
    username: craigiswayne
    shareID: 259d6e52-3683-4102-a313-3a777ccc3614

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  - .idea/
  - dotfiles/
  - src/
  - budget.json
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
