"use strict";this.default_datachannel=this.default_datachannel||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,da,ea;_.n=function(a){return void 0!==a};ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};da=function(a,b,c){return a.call.apply(a.bind,arguments)};
ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.t=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.wd=function(a,c,f){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[c].apply(a,g)}};
_.ga=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.q=function(a,b,c){_.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return _.q.apply(null,arguments)};
_.ia=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ja=function(a){return"function"==ea(a)};_.ka=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.la=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ma=function(a){return"array"==ea(a)};_.oa=function(){};_.qa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.qa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}; _.p(_.qa,Error);_.qa.prototype.name="CustomError";
var ra=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ta=function(a,b){for(var c=0,d=ra(String(a)).split("."),e=ra(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var l=d[g]||"",r=e[g]||"",C=RegExp("(\\d*)(\\D*)","g"),N=RegExp("(\\d*)(\\D*)","g");do{var fa=C.exec(l)||["","",""],Q=N.exec(r)||["","",""];if(0==fa[0].length&&0==Q[0].length)break;c=sa(0==fa[1].length?0:(0,window.parseInt)(fa[1],10),0==Q[1].length?0:(0,window.parseInt)(Q[1], 10))||sa(0==fa[2].length,0==Q[2].length)||sa(fa[2],Q[2])}while(0==c)}return c},sa=function(a,b){return a<b?-1:a>b?1:0};
_.u=Array.prototype;_.ua=_.u.indexOf?function(a,b,c){return _.u.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.va=_.u.lastIndexOf?function(a,b,c){return _.u.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.v=_.u.forEach?function(a,b,c){_.u.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.wa=_.u.filter?function(a,b,c){return _.u.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.t(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var r=g[l];b.call(c,r,l,a)&&(e[f++]=r)}return e};_.xa=_.u.map?function(a,b,c){return _.u.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.ya=_.u.reduce?function(a,b,c,d){d&&(b=(0,_.q)(b,d));return _.u.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.v)(a,function(c,g){e=b.call(d,e,c,g,a)});return e};_.za=_.u.some?function(a,b,c){return _.u.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Aa=function(a,b){var c=(0,_.ua)(a,b),d;(d=0<=c)&&_.u.splice.call(a,c,1);return d};
_.Ba=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var Da,Fa;_.Ca=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Da=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Ea=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Fa=function(a){var b=arguments.length;if(1==b&&_.ma(arguments[0]))return Fa.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var Ha;_.w=function(){};_.x=function(a,b,c,d){a.a=null;b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.c=0===c?-1:0;a.F=b;a:{if(a.F.length&&(b=a.F.length-1,(c=a.F[b])&&"object"==typeof c&&!_.ma(c))){a.j=b-a.c;a.b=c;break a}a.j=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.c,a.F[c]=a.F[c]||_.Ga):a.b[c]=a.b[c]||_.Ga};_.Ga=[];_.y=function(a,b){if(b<a.j){var c=b+a.c,d=a.F[c];return d===_.Ga?a.F[c]=[]:d}d=a.b[b];return d===_.Ga?a.b[b]=[]:d};_.w.prototype.toString=function(){return this.F.toString()}; _.z=function(a,b){Ha[a]=b;b.messageId=a};Ha={};
Fa("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));_.Ia="StopIteration"in _.k?_.k.StopIteration:Error("f");_.Ja=function(){};_.Ja.prototype.next=function(){throw _.Ia;};_.Ja.prototype.ha=function(){return this};a:{var La=_.k.navigator;if(La){var Ma=La.userAgent;if(Ma){_.Ka=Ma;break a}}_.Ka=""}var A=function(a){return-1!=_.Ka.indexOf(a)};var Na=function(){return A("Opera")||A("OPR")},Oa=function(){return A("Edge")||A("Trident")||A("MSIE")},Pa=function(){return(A("Chrome")||A("CriOS"))&&!Na()&&!Oa()};var Qa=function(){return A("Edge")};var Ra=function(){return A("iPhone")&&!A("iPod")&&!A("iPad")};_.B=function(a,b){this.b={};this.a=[];this.j=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.B?(c=a.M(),d=a.B()):(c=_.Ea(a),d=Da(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.B.prototype.V=function(){return this.c};_.B.prototype.B=function(){Sa(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.B.prototype.M=function(){Sa(this);return this.a.concat()};
_.Ua=function(a,b){return Ta(a.b,b)};_.B.prototype.P=function(){return 0==this.c};_.B.prototype.clear=function(){this.b={};this.j=this.c=this.a.length=0};_.B.prototype.remove=function(a){return Ta(this.b,a)?(delete this.b[a],this.c--,this.j++,this.a.length>2*this.c&&Sa(this),!0):!1};
var Sa=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Ta(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Ta(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.B.prototype;_.h.get=function(a,b){return Ta(this.b,a)?this.b[a]:b};_.h.set=function(a,b){Ta(this.b,a)||(this.c++,this.a.push(a),this.j++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.h.clone=function(){return new _.B(this)};_.h.ha=function(a){Sa(this);var b=0,c=this.a,d=this.b,e=this.j,f=this,g=new _.Ja;g.next=function(){for(;;){if(e!=f.j)throw Error("i");if(b>=c.length)throw _.Ia;var g=c[b++];return a?g:d[g]}};return g};var Ta=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Va=function(a){if("function"==typeof a.B)return a.B();if(_.t(a))return a.split("");if(_.la(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Da(a)};
_.Wa=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.la(a)||_.t(a))(0,_.v)(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.B)if(_.la(a)||_.t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=_.Ea(a);else d=void 0;for(var e=_.Va(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};
var Xa,Za,$a,bb,cb,db,fb,hb,ib,jb;Xa=Na();_.D=Oa();_.Ya=A("Gecko")&&!(-1!=_.Ka.toLowerCase().indexOf("webkit")&&!Qa())&&!(A("Trident")||A("MSIE"))&&!Qa();Za=-1!=_.Ka.toLowerCase().indexOf("webkit")&&!Qa();$a=_.k.navigator||null;_.ab=$a&&$a.platform||"";bb=function(){var a=_.Ka;if(_.Ya)return/rv\:([^\);]+)(\)|;)/.exec(a);if(_.D&&Qa())return/Edge\/([\d\.]+)/.exec(a);if(_.D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Za)return/WebKit\/(\S+)/.exec(a)};
cb=function(){var a=_.k.document;return a?a.documentMode:void 0};db=function(){if(Xa&&_.k.opera){var a=_.k.opera.version;return _.ja(a)?a():a}var a="",b=bb();b&&(a=b?b[1]:"");return _.D&&!Qa()&&(b=cb(),b>(0,window.parseFloat)(a))?String(b):a}();fb={};_.gb=function(a){return fb[a]||(fb[a]=0<=ta(db,a))};hb=_.k.document;ib=cb();jb=!hb||!_.D||!ib&&Qa()?void 0:ib||("CSS1Compat"==hb.compatMode?(0,window.parseInt)(db,10):5);
_.E=function(){this.C=this.C;this.j=this.j};_.E.prototype.C=!1;_.E.prototype.xb=function(){return this.C};_.E.prototype.D=function(){this.C||(this.C=!0,this.n())};_.G=function(a,b){_.kb(a,_.ha(_.F,b))};_.kb=function(a,b){a.C?b.call(void 0):(a.j||(a.j=[]),a.j.push(_.n(void 0)?(0,_.q)(b,void 0):b))};_.E.prototype.n=function(){if(this.j)for(;this.j.length;)this.j.shift()()};_.F=function(a){a&&"function"==typeof a.D&&a.D()};
_.lb=!_.D||_.D&&(Qa()||9<=jb);!_.Ya&&!_.D||_.D&&_.D&&(Qa()||9<=jb)||_.Ya&&_.gb("1.9.1");_.D&&_.gb("9");var mb=function(a){mb[" "](a);return a};mb[" "]=_.oa;_.nb=function(a,b){try{return mb(a[b]),!0}catch(c){}return!1};var ob,pb;ob=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.rb=function(a){if(pb){pb=!1;var b=_.k.location;if(b){var c=b.href;if(c&&(c=_.qb(c))&&c!=b.hostname)throw pb=!0,Error();}}return a.match(ob)};pb=Za;_.qb=function(a){return(a=_.rb(a)[3]||null)?(0,window.decodeURI)(a):a};
var sb=!_.D||_.D&&(Qa()||9<=jb),tb=_.D&&!_.gb("9");!Za||_.gb("528");_.Ya&&_.gb("1.9b")||_.D&&_.gb("8")||Xa&&_.gb("9.5")||Za&&_.gb("528");_.Ya&&!_.gb("8")||_.D&&_.gb("9");_.H=function(a,b){this.type=a;this.a=this.target=b;this.mc=!0};_.H.prototype.b=function(){this.mc=!1};var ub=function(a,b){_.H.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&_.Ya&&_.nb(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};_.p(ub,_.H); ub.prototype.b=function(){ub.t.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,tb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var vb,xb;vb="closure_listenable_"+(1E6*Math.random()|0);_.wb=function(a){return!(!a||!a[vb])};xb=0;var yb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ta=!!d;this.$a=e;this.key=++xb;this.removed=this.Sa=!1},zb=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.$a=null};var Ab=function(a){this.src=a;this.a={};this.b=0};Ab.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Bb(a,b,d,e);-1<g?(b=a[g],c||(b.Sa=!1)):(b=new yb(b,this.src,f,!!d,e),b.Sa=c,a.push(b));return b};Ab.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Bb(e,b,c,d);return-1<b?(zb(e[b]),_.u.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Cb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.Aa(a.a[c],b);d&&(zb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};Ab.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,zb(d[e]);delete this.a[c];this.b--}return b}; var Db=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Bb(a,c,d,e));return-1<b?a[b]:null},Bb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ta==!!c&&f.$a==d)return e}return-1};
var Eb,Fb,Gb,Lb,Nb,Sb,Rb,Ob,Kb,Tb;Eb="closure_lm_"+(1E6*Math.random()|0);Fb={};Gb=0;_.Hb=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)_.Hb(a,b[f],c,d,e);return null}c=_.Ib(c);return _.wb(a)?a.listen(b,c,d,e):_.Jb(a,b,c,!1,d,e)};_.Jb=function(a,b,c,d,e,f){if(!b)throw Error("l");var g=!!e,l=Kb(a);l||(a[Eb]=l=new Ab(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=Lb();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Nb(b.toString()),d);Gb++;return c};
Lb=function(){var a=Ob,b=sb?function(c){return a.call(b.src,b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b};_.Pb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)_.Pb(a,b[f],c,d,e);else c=_.Ib(c),_.wb(a)?a.Eb(b,c,d,e):a&&(a=Kb(a))&&(b=Db(a,b,c,!!d,e))&&_.Qb(b)};
_.Qb=function(a){if(_.ka(a)||!a||a.removed)return!1;var b=a.src;if(_.wb(b))return Cb(b.U,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ta):b.detachEvent&&b.detachEvent(Nb(c),d);Gb--;(c=Kb(b))?(Cb(c,a),0==c.b&&(c.src=null,b[Eb]=null)):zb(a);return!0};Nb=function(a){return a in Fb?Fb[a]:Fb[a]="on"+a};Sb=function(a,b,c,d){var e=!0;if(a=Kb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ta==c&&!f.removed&&(f=Rb(f,d),e=e&&!1!==f)}return e};
Rb=function(a,b){var c=a.qa,d=a.$a||a.src;a.Sa&&_.Qb(a);return c.call(d,b)};
Ob=function(a,b){if(a.removed)return!0;if(!sb){var c;if(!(c=b))a:{c=["window","event"];for(var d=_.k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new ub(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--){c.a=e[l];var r=Sb(e[l],f,!0,c),d=d&&r}for(l=0;l<e.length;l++)c.a=e[l],r=Sb(e[l],
f,!1,c),d=d&&r}return d}return Rb(a,new ub(b,this))};Kb=function(a){a=a[Eb];return a instanceof Ab?a:null};Tb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Ib=function(a){if(_.ja(a))return a;a[Tb]||(a[Tb]=function(b){return a.handleEvent(b)});return a[Tb]};
_.Ub=function(a){_.x(this,a,"h_cc",null)};_.p(_.Ub,_.w);_.z("h_cc",_.Ub);_.Ub.prototype.Z=function(){return _.y(this,19)};_.I=function(a){_.E.call(this);this.I=a;this.g={}};_.p(_.I,_.E);var Vb=[];_.I.prototype.listen=function(a,b,c,d){return _.Wb(this,a,b,c,d)};_.Wb=function(a,b,c,d,e,f){_.ma(c)||(c&&(Vb[0]=c.toString()),c=Vb);for(var g=0;g<c.length;g++){var l=_.Hb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!l)break;a.g[l.key]=l}return a};
_.I.prototype.Eb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)this.Eb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.Ib(c),d=!!d,b=_.wb(a)?Db(a.U,String(b),c,d,e):a?(a=Kb(a))?Db(a,b,c,d,e):null:null,b&&(_.Qb(b),delete this.g[b.key]);return this};_.I.prototype.removeAll=function(){_.Ca(this.g,_.Qb);this.g={}};_.I.prototype.n=function(){_.I.t.n.call(this);this.removeAll()};_.I.prototype.handleEvent=function(){throw Error("m");};
var Xb=function(a,b,c){this.j=c;this.c=a;this.e=b;this.b=0;this.a=null};Xb.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var Yb=function(a,b){a.e(b);a.b<a.j&&(a.b++,b.next=a.a,a.a=b)};var Zb,$b,ac;Zb=function(a){_.k.setTimeout(function(){throw a;},0)};_.bc=function(a,b){var c=a;b&&(c=(0,_.q)(a,b));!_.ja(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype&&_.k.Window.prototype.setImmediate==_.k.setImmediate?($b||($b=ac()),$b(c)):_.k.setImmediate(c)};
ac=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!A("Presto")&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.q)(function(a){if(("*"==d||
a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Oa()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Qb;c.Qb=null;a()}};return function(a){d.next={Qb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")?function(a){var b=window.document.createElement("script"); b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};
var cc=function(){this.b=this.a=null},ec=new Xb(function(){return new dc},function(a){a.reset()},100);cc.prototype.add=function(a,b){var c=ec.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};cc.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var dc=function(){this.next=this.b=this.a=null};dc.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};dc.prototype.reset=function(){this.next=this.b=this.a=null};
var jc=function(a,b){fc||gc();hc||(fc(),hc=!0);ic.add(a,b)},fc,gc=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve();fc=function(){a.then(kc)}}else fc=function(){_.bc(kc)}},hc=!1,ic=new cc,kc=function(){for(var a=null;a=ic.remove();){try{a.a.call(a.b)}catch(b){Zb(b)}Yb(ec,a)}hc=!1};
_.J=function(){_.E.call(this);this.U=new Ab(this);this.L=this;this.u=null};_.p(_.J,_.E);_.J.prototype[vb]=!0;_.h=_.J.prototype;_.h.addEventListener=function(a,b,c,d){_.Hb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.Pb(this,a,b,c,d)};_.h.n=function(){_.J.t.n.call(this);this.U&&this.U.removeAll(void 0);this.u=null};_.h.listen=function(a,b,c,d){return this.U.add(String(a),b,!1,c,d)};_.h.Eb=function(a,b,c,d){return this.U.remove(String(a),b,c,d)}; _.h.da=function(a,b,c){a=this.U.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ta==b){var g=f.qa,l=f.$a||f.src;f.Sa&&Cb(this.U,f);d=!1!==g.call(l,c)&&d}}return d&&0!=c.mc};
var lc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},mc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var pc=function(a,b){this.a=0;this.g=void 0;this.j=this.b=this.c=null;this.e=this.f=!1;if(a==nc)oc(this,2,b);else try{var c=this;a.call(b,function(a){oc(c,2,a)},function(a){oc(c,3,a)})}catch(d){oc(this,3,d)}},qc=function(){this.next=this.b=this.j=this.c=this.a=null},rc,sc,nc;qc.prototype.reset=function(){this.b=this.j=this.c=this.a=null};rc=new Xb(function(){return new qc},function(a){a.reset()},100);sc=function(){var a=rc.get();a.c=null;a.j=null;a.b=null;return a};nc=function(){};
_.uc=function(){var a,b=new pc(function(b){a=b});return new tc(b,a)};pc.prototype.then=function(a,b,c){return vc(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};lc(pc);
var yc=function(a){0==a.a&&jc(function(){var a=new wc(void 0);xc(this,a)},a)},xc=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,g=c.b;g;g=g.next){var l=g.a;if(l&&(d++,l==a&&(e=g),e&&1<d))break;e||(f=g)}e&&(0==c.a&&1==d?xc(c,b):(f?(d=f,d.next==c.j&&(c.j=d),d.next=d.next.next):zc(c),Ac(c,e,3,b)))}a.c=null}else oc(a,3,b)},Cc=function(a,b){a.b||2!=a.a&&3!=a.a||Bc(a);a.j?a.j.next=b:a.b=b;a.j=b},vc=function(a,b,c,d){var e=sc();e.a=new pc(function(a,g){e.c=b?function(c){try{var e=
b.call(d,c);a(e)}catch(C){g(C)}}:a;e.j=c?function(b){try{var e=c.call(d,b);!_.n(e)&&b instanceof wc?g(b):a(e)}catch(C){g(C)}}:g});e.a.c=a;Cc(a,e);return e.a};pc.prototype.h=function(a){this.a=0;oc(this,2,a)};pc.prototype.k=function(a){this.a=0;oc(this,3,a)};
var oc=function(a,b,c){if(0==a.a){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(mc(c)){a.a=1;c.then(a.h,a.k,a);return}if(_.ia(c))try{var d=c.then;if(_.ja(d)){Dc(a,c,d);return}}catch(e){b=3,c=e}}a.g=c;a.a=b;a.c=null;Bc(a);3!=b||c instanceof wc||Ec(a,c)}},Dc=function(a,b,c){a.a=1;var d=!1,e=function(b){d||(d=!0,a.h(b))},f=function(b){d||(d=!0,a.k(b))};try{c.call(b,e,f)}catch(g){f(g)}},Bc=function(a){a.f||(a.f=!0,jc(a.l,a))},zc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,
b.next=null);a.b||(a.j=null);return b};pc.prototype.l=function(){for(var a=null;a=zc(this);)Ac(this,a,this.a,this.g);this.f=!1};var Ac=function(a,b,c,d){b.a&&(b.a.c=null);if(2==c)b.c.call(b.b,d);else{if(b.a)for(;a&&a.e;a=a.c)a.e=!1;b.j.call(b.b,d)}Yb(rc,b)},Ec=function(a,b){a.e=!0;jc(function(){a.e&&Fc.call(null,b)})},Fc=Zb,wc=function(a){_.qa.call(this,a)};_.p(wc,_.qa);wc.prototype.name="cancel";var tc=function(a,b){this.b=a;this.a=b};
var Hc,Ic,Jc,Kc,Lc;_.Gc=A("Firefox");Hc=Ra()||A("iPod");Ic=A("iPad");Jc=A("Android")&&!(Pa()||A("Firefox")||Na()||A("Silk"));Kc=Pa();Lc=A("Safari")&&!(Pa()||A("Coast")||Na()||Oa()||A("Silk")||A("Android"))&&!(Ra()||A("iPad")||A("iPod"));_.Mc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Nc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.Oc=function(a,b){this.j=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.e=null;this.h=b||"u";this.a=this.g=null;this.f=[]};_.Oc.prototype.message=function(){var a={};a.i=this.a;a.m=this.f;a.r=this.h;a.o=this.g;a.s=this.b;a.st=this.c;a.d=this.e;a.dt=this.j;return a};_.ga("ace.base.Message.prototype.message",_.Oc.prototype.message);
_.Pc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.a=b[c];break;case "m":a.f=b[c];break;case "o":a.g=b[c];break;case "s":a.b=b[c];break;case "d":a.e=b[c];break;case "st":a.c=b[c];break;case "dt":a.j=b[c]}return a};_.Qc=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))};_.Rc=function(a,b){null!=b&&(a.a=b)};_.Sc=function(a,b){"object"==typeof b?a.f=b:a.f=[b]};_.Oc.prototype.source=function(){return this.b};_.Oc.prototype.target=function(){return this.e}; _.Oc.prototype.content=function(){return this.f};
_.Tc=function(a,b,c,d,e){_.E.call(this);this.b=a;this.Pa=b;this.a=typeof b;this.zb=c?c:!1;this.ba=!0;this.vb=d?d:!1;this.pb=e?e:!1};_.p(_.Tc,_.E);_.h=_.Tc.prototype;_.h.n=function(){_.Tc.t.n.call(this);this.b="";this.Pa=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.G=function(){return this.Pa};_.h.setEnabled=function(a){this.ba=a};
var Uc=function(a){return(a=a.exec(_.Ka))?a[1]:""},Vc=function(){if(_.Gc)return Uc(/Firefox\/([0-9.]+)/);if(_.D||Xa)return db;if(Kc)return Uc(/Chrome\/([0-9.]+)/);if(Lc&&!(Ra()||A("iPad")||A("iPod")))return Uc(/Version\/([0-9.]+)/);if(Hc||Ic){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Ka))return a[1]+"."+a[2]}else if(Jc)return(a=Uc(/Android\s+([0-9.]+)/))?a:Uc(/Version\/([0-9.]+)/);return""}();
_.Xc=function(a){_.E.call(this);this.a=new _.B;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&_.Wc(this,a)};_.p(_.Xc,_.E);_.Yc=0<=ta(Vc,"23.0.1262.0")&&!_.Nc();_.Xc.prototype.n=function(){_.Xc.t.n.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.F(this.a.get(a[b]));delete this.a};_.Xc.prototype.getItem=function(a){return _.Ua(this.a,a)?this.a.get(a):null};
_.Xc.prototype.setItem=function(a){this.a.set(a.id(),a)};_.Wc=function(a,b){for(var c in b){var d=b[c],e=null;_.Ua(a.a,c)?(e=a.a.get(c),e.Pa=d.value,d.changed&&(e.pb=d.changed)):(e=new _.Tc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.ad=function(){this.c=new _.B;this.a=null;this.b=!1;this.a=new Zc;this.b=!0;_.$c(this)};_.ad.ua=function(){return _.ad.a?_.ad.a:_.ad.a=new _.ad};_.$c=function(a,b){var c=b||_.oa;a.b?c():window.chrome.storage.local.get((0,_.q)(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};_.ad.prototype.get=function(a){return this.a.get(a)};_.ad.prototype.set=function(a,b){var c=_.uc();this.a.set(a,b);c.a(void 0);return c.b};_.ad.prototype.remove=function(a){this.a.remove(a)};
_.ad.prototype.clear=function(){this.a.clear()};var Zc=function(){this.a=window.localStorage};Zc.prototype.clear=function(){this.a.clear()};Zc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ha[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};Zc.prototype.set=function(a,b){var c=null;b instanceof _.w&&(b=b.F,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}}; Zc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
_.bd=function(a,b){this.b=a;this.a=b;this.constructor.Ob||(this.constructor.Ob={});this.constructor.Ob[this.toString()]=this};_.bd.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};_.K=function(a,b){_.bd.call(this,a,b)};_.p(_.K,_.bd);_.cd=function(a){this.a=a};_.dd=new _.cd("lib");_.L=function(a){this.a=a};_.L.prototype.toString=function(){return this.a};_.ed=new _.L("fJuxOc");_.fd=new _.L("ZtVrH");_.gd=new _.L("zZa4xc");_.hd=new _.L("pVbxBc");_.id=new _.L("byfTOb");_.jd=new _.L("LEikZe");_.kd=new _.L("rJmJrc");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.ld=function(a,b){this.j=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.f=!1;this.e=0;this.h=null;this.q=0};_.ld.prototype.k=function(a,b){this.f=!1;_.md(this,a,b)};_.md=function(a,b,c){a.a=!0;a.c=c;a.b=!b;nd(a)};_.pd=function(a){if(a.a){if(!a.l)throw new od;a.l=!1}};_.ld.prototype.g=function(a){_.pd(this);_.md(this,!0,a)};_.qd=function(a,b,c,d){a.j.push([b,c,d]);a.a&&nd(a)};
_.ld.prototype.then=function(a,b,c){var d,e,f=new pc(function(a,b){d=a;e=b});_.qd(this,d,function(a){"undefined"!=typeof _.rd&&a instanceof _.rd?yc(f):e(a)});return f.then(a,b,c)};lc(_.ld);
var sd=function(a){return(0,_.za)(a.j,function(a){return _.ja(a[1])})},nd=function(a){if(a.e&&a.a&&sd(a)){var b=a.e,c=td[b];c&&(_.k.clearTimeout(c.Wa),delete td[b]);a.e=0}a.h&&(a.h.q--,delete a.h);for(var b=a.c,d=c=!1;a.j.length&&!a.f;){var e=a.j.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var l=f.call(e||a.u,b);_.n(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);mc(b)&&(d=!0,a.f=!0)}catch(r){b=r,a.b=!0,sd(a)||(c=!0)}}a.c=b;d&&(l=(0,_.q)(a.k,a,!0),d=(0,_.q)(a.k,a,!1),b instanceof _.ld?(_.qd(b,
l,d),b.p=!0):b.then(l,d));c&&(b=new ud(b),td[b.Wa]=b,a.e=b.Wa)},od=function(){_.qa.call(this)};_.p(od,_.qa);od.prototype.message="Deferred has already fired";od.prototype.name="AlreadyCalledError";var ud=function(a){this.Wa=_.k.setTimeout((0,_.q)(this.b,this),0);this.a=a};ud.prototype.b=function(){delete td[this.Wa];throw this.a;};var td={};

}catch(e){_._DumpException(e)}
try{
var wd;_.vd=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};wd=function(a,b){for(var c=_.t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};_.yd=function(a){_.E.call(this);this.c={};this.h={};this.k={};this.e={};this.l={};this.q={};this.p=a?a.ta():new _.J;this.w=!a;this.f=null;a?(this.f=a,this.k=a.k,this.e=a.e,this.h=a.h,this.l=a.l):(0,_.m)();a=xd(this);this!=a&&(a.g?a.g.push(this):a.g=[this])};_.p(_.yd,_.E);var xd=function(a){for(;a.f;)a=a.f;return a};_.yd.prototype.get=function(a){var b=this.b(a);if(null==b)throw new zd(a);return b};
_.yd.prototype.b=function(a){for(var b=this;b;b=b.f){if(b.C)throw Error("q");if(b.c[a])return b.c[a][0];if(b.q[a])break}if(b=this.k[a]){b=b(this);if(null==b)throw Error("r`"+a);this.a(a,b);return b}return null};_.yd.prototype.a=function(a,b,c){if(this.C)c||_.F(b);else{this.c[a]=[b,!c];b=Ad(this,this,a);for(c=0;c<b.length;c++)b[c].g(null);delete this.h[a]}};_.yd.prototype.u=function(){var a=_.Bd;if(!this.c[a])throw Error("s`"+a);var b=this.c[a];delete this.c[a];b[1]&&_.F(b[0])};
var Ad=function(a,b,c){var d=[],e=a.e[c];e&&(wd(e,function(a){var c;a:{for(c=a.Pb;c;){if(c==b){c=!0;break a}c=c.f}c=!1}c&&(d.push(a.xd),_.Aa(e,a))}),0==e.length&&delete a.e[c]);return d},Cd=function(a,b){a.e&&_.Wa(a.e,function(a,d,e){wd(a,function(d){d.Pb==b&&_.Aa(a,d)});0==a.length&&delete e[d]})};
_.yd.prototype.n=function(){if(xd(this)==this){var a=this.g;if(a)for(;a.length;)a[0].D()}else for(var a=xd(this).g,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&"undefined"!=typeof a[0].D&&a[0].D();this.c=null;this.w&&this.p.D();Cd(this,this);this.e=null;_.F(this.v);this.q=this.v=null;_.yd.t.n.call(this)};_.yd.prototype.ta=function(){return this.p};var zd=function(a){_.qa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'}; _.p(zd,_.qa);var Dd=new _.cd("fva");new _.K(Dd,1);

}catch(e){_._DumpException(e)}
try{
var Ed,Fd,Gd,Id,Jd,Kd,Ld,Rd,Sd,Td,Xd,Yd,ae,be,ce,de,ee,fe,ge,le;Ed={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};Fd=function(a,b){b.push('"',a.replace(_.Ba,function(a){if(a in Ed)return Ed[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Ed[a]=e+b.toString(16)}),'"')};
Gd=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)Gd(a,b[f],c,d,e);return null}c=_.Ib(c);return _.wb(a)?a.U.add(String(b),c,!0,d,e):_.Jb(a,b,c,!0,d,e)};Id="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
Jd=function(a,b,c){switch(typeof b){case "string":Fd(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(_.ma(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),Jd(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),Fd(e,c),c.push(":"),
Jd(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("d`"+typeof b);}};Kd=function(){};Ld=function(a,b,c,d,e,f){if(_.ma(c))for(var g=0;g<c.length;g++)Ld(a,b,c[g],d,e,f);else{b=Gd(b,c,d||a.handleEvent,e,f||a.I||a);if(!b)return a;a.g[b.key]=b}return a};_.M=function(a,b,c){b<a.j?a.F[b+a.c]=c:a.b[b]=c};
_.Md=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Id.length;f++)c=Id[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.Nd=function(a){var b=[];Jd(new Kd,a,b);return b.join("")};_.Od=function(a,b,c){null!=b&&(a.e=b,null!=c&&(a.j=c))};
_.O=function(a,b){var c,d=a.u;if(d)for(c=[];d;d=d.u)c.push(d);var d=a.L,e=b,f=e.type||e;if(_.t(e))e=new _.H(e,d);else if(e instanceof _.H)e.target=e.target||d;else{var g=e,e=new _.H(f,d);_.Md(e,g)}var g=!0,l;if(c)for(var r=c.length-1;0<=r;r--)l=e.a=c[r],g=l.da(f,!0,e)&&g;l=e.a=d;g=l.da(f,!0,e)&&g;g=l.da(f,!1,e)&&g;if(c)for(r=0;r<c.length;r++)l=e.a=c[r],g=l.da(f,!1,e)&&g};_.Pd=function(a,b,c,d){return Ld(a,b,c,d,void 0)};_.Qd=function(a,b,c){a.a||(a.a={});var d=c?c.F:c;a.a[b]=c;_.M(a,b,d)};
_.P=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=_.y(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};Rd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Sd=function(a,b){return a?b?(0,window.decodeURI)(a):(0,window.decodeURIComponent)(a):""};Td=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};
_.Ud=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.Vd=function(a){return _.u.concat.apply(_.u,arguments)};_.Wd=function(a,b,c){this.a=a||null;this.b=!!c};Xd=function(a){a.H||(a.H=new _.B,a.O=0,a.a&&Td(a.a,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};_.h=_.Wd.prototype;_.h.H=null;_.h.O=null;_.h.V=function(){Xd(this);return this.O};
_.h.add=function(a,b){Xd(this);this.a=null;a=Yd(this,a);var c=this.H.get(a);c||this.H.set(a,c=[]);c.push(b);this.O++;return this};_.h.remove=function(a){Xd(this);a=Yd(this,a);return _.Ua(this.H,a)?(this.a=null,this.O-=this.H.get(a).length,this.H.remove(a)):!1};_.h.clear=function(){this.H=this.a=null;this.O=0};_.h.P=function(){Xd(this);return 0==this.O};var Zd=function(a,b){Xd(a);b=Yd(a,b);return _.Ua(a.H,b)};
_.Wd.prototype.M=function(){Xd(this);for(var a=this.H.B(),b=this.H.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.Wd.prototype.B=function(a){Xd(this);var b=[];if(_.t(a))Zd(this,a)&&(b=_.Vd(b,this.H.get(Yd(this,a))));else{a=this.H.B();for(var c=0;c<a.length;c++)b=_.Vd(b,a[c])}return b};_.Wd.prototype.set=function(a,b){Xd(this);this.a=null;a=Yd(this,a);Zd(this,a)&&(this.O-=this.H.get(a).length);this.H.set(a,[b]);this.O++;return this};
_.Wd.prototype.get=function(a,b){var c=a?this.B(a):[];return 0<c.length?String(c[0]):b};_.$d=function(a,b,c){a.remove(b);0<c.length&&(a.a=null,a.H.set(Yd(a,b),_.Ud(c)),a.O+=c.length)};_.Wd.prototype.toString=function(){if(this.a)return this.a;if(!this.H)return"";for(var a=[],b=this.H.M(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.B(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}return this.a=a.join("&")};
_.Wd.prototype.clone=function(){var a=new _.Wd;a.a=this.a;this.H&&(a.H=this.H.clone(),a.O=this.O);return a};Yd=function(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c};ae=function(a,b){b&&!a.b&&(Xd(a),a.a=null,a.H.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.$d(this,e,a))},a));a.b=b};be=/#/g;ce=/[\#\?@]/g;de=/[\#\?]/g;ee=/[\#\?:]/g;fe=/[#\/\?@]/g;
ge=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,Rd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};_.he=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36)};
_.ie=function(a,b){var c;"undefined"!=typeof _.ie&&a instanceof _.ie?(this.ma=_.n(b)?b:a.ma,_.je(this,a.fa),this.sa=a.sa,this.R=a.R,_.ke(this,a.ea),this.N=a.N,le(this,a.a.clone()),this.la=a.la):a&&(c=_.rb(String(a)))?(this.ma=!!b,_.je(this,c[1]||"",!0),this.sa=Sd(c[2]||""),this.R=Sd(c[3]||"",!0),_.ke(this,c[4]),this.N=Sd(c[5]||"",!0),le(this,c[6]||"",!0),this.la=Sd(c[7]||"")):(this.ma=!!b,this.a=new _.Wd(null,0,this.ma))};_.h=_.ie.prototype;_.h.fa="";_.h.sa="";_.h.R="";_.h.ea=null;_.h.N="";
_.h.la="";_.h.ma=!1;_.h.toString=function(){var a=[],b=this.fa;b&&a.push(ge(b,fe,!0),":");if(b=this.R){a.push("//");var c=this.sa;c&&a.push(ge(c,fe,!0),"@");a.push((0,window.encodeURIComponent)(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.ea;null!=b&&a.push(":",String(b))}if(b=this.N)this.R&&"/"!=b.charAt(0)&&a.push("/"),a.push(ge(b,"/"==b.charAt(0)?de:ee,!0));(b=this.a.toString())&&a.push("?",b);(b=this.la)&&a.push("#",ge(b,be));return a.join("")};
_.me=function(a,b){var c=a.clone(),d=!!b.fa;d?_.je(c,b.fa):d=!!b.sa;d?c.sa=b.sa:d=!!b.R;d?c.R=b.R:d=null!=b.ea;var e=b.N;if(d)_.ke(c,b.ea);else if(d=!!b.N){if("/"!=e.charAt(0))if(a.R&&!a.N)e="/"+e;else{var f=c.N.lastIndexOf("/");-1!=f&&(e=c.N.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),g=[],l=0;l<f.length;){var r=f[l++];"."==r?e&&l==f.length&&g.push(""):".."==r?((1<g.length||1==g.length&&""!=g[0])&&
g.pop(),e&&l==f.length&&g.push("")):(g.push(r),e=!0)}e=g.join("/")}else e=f}d?c.N=e:d=""!==b.a.toString();d?le(c,Sd(b.a.toString())):d=!!b.la;d&&(c.la=b.la);return c};_.ie.prototype.clone=function(){return new _.ie(this)};_.je=function(a,b,c){a.fa=c?Sd(b,!0):b;a.fa&&(a.fa=a.fa.replace(/:$/,""))};_.ke=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("j`"+b);a.ea=b}else a.ea=null};le=function(a,b,c){b instanceof _.Wd?(a.a=b,ae(a.a,a.ma)):(c||(b=ge(b,ce)),a.a=new _.Wd(b,0,a.ma))};
_.R=function(a,b,c){a.a.set(b,c)};_.ne=function(a,b,c){_.ma(c)||(c=[String(c)]);_.$d(a.a,b,c)};_.oe=function(a,b){return a.a.get(b)};_.pe=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.qe=function(a,b){return 0<=(0,_.ua)(a,b)};
_.re=function(a,b,c){if(_.ja(a))c&&(a=(0,_.q)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.q)(a.handleEvent,a);else throw Error("n");return 2147483647<b?-1:_.k.setTimeout(a,b||0)};_.se=function(a){_.k.clearTimeout(a)};_.te=function(a){var b={},c;for(c in a)b[c]=a[c];return b};_.ue=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.la(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}}; _.ve=function(a,b){var c;a:{c=a.length;for(var d=_.t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:_.t(a)?a.charAt(c):a[c]};
var ze,xe,ye,Ae;_.we=function(){};ze=function(a){var b=a.ia,c=function(a){c.t.constructor.call(this,a);var b=this.T.length;this.a=[];for(var d=0;d<b;++d)this.T[d].yd||(this.a[d]=new this.T[d](a))};_.p(c,b);for(var d=[];a;){if(b=a.ia){b.T&&_.ue(d,b.T);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ja(e[f])&&e[f]!==b){var g=!!e[f].Jc,l=xe(f,e,d,g);(g=ye(f,e,l,g))&&(c.prototype[f]=g)}}a=a.t&&a.t.constructor}c.prototype.T=d;return c};
xe=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e};
ye=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.T[c[0]].prototype[a].apply(this,arguments)}:b[a].Lc?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var r=this.a[c[e]];if(r=r?r[a].apply(r,d):this.T[c[e]].prototype[a].apply(this,d)){d=r;break a}}d=!1}return d}:b[a].Kc?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var r=this.a[c[e]],r=r?r[a].apply(r,
d):this.T[c[e]].prototype[a].apply(this,d);if(null!=r){d=r;break a}}d=void 0}return d}:b[a].gc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var r=this.a[c[e]];r?r[a].apply(r,d):this.T[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],r=0;r<c.length;++r){var C=this.a[c[r]];e.push(C?C[a].apply(C,d):this.T[c[r]].prototype[a].apply(this,d))}return e}:d||b[a].Lc||b[a].Kc||b[a].gc?e=null:e=Ae;return e};Ae=function(){return[]}; _.we.prototype.tb=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var Be;_.Ce=function(a){if(!a.qb){var b;for(b=a.constructor;b&&!b.ia;)b=b.t&&b.t.constructor;b.ia.Tb||(b.ia.Tb=ze(b));b=new b.ia.Tb(a);a.qb=b;a.tb||(a.tb=Be)}};Be=function(a){return this.qb.tb(a)};var De=function(){};De.prototype.a=null;var Fe=function(a){var b;(b=a.a)||(b={},Ee(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var Ge,He=function(){};_.p(He,De);var Ie=function(a){return(a=Ee(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},Ee=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("t");}return a.b};Ge=new He;
var Ke,Ne,Se,Ue,Te,Pe;_.Je=function(a){_.J.call(this);this.A=new _.B;this.k=a||null;this.b=!1;this.h=this.a=null;this.q="";this.e=0;this.c=this.p=this.f=this.l=!1;this.v=0;this.g=null;this.I="";this.w=this.aa=!1};_.p(_.Je,_.J);Ke=/^https?$/i;_.Le=["POST","PUT"];_.Me=[];_.Je.prototype.S=function(){this.D();_.Aa(_.Me,this)};
_.Je.prototype.send=function(a,b,c,d){if(this.a)throw Error("u`"+this.q+"`"+a);b=b?b.toUpperCase():"GET";this.q=a;this.e=0;this.l=!1;this.b=!0;this.a=this.k?Ie(this.k):Ie(Ge);this.h=this.k?Fe(this.k):Fe(Ge);this.a.onreadystatechange=(0,_.q)(this.J,this);try{this.p=!0,this.a.open(b,String(a),!0),this.p=!1}catch(e){Ne(this);return}a=c||"";var f=this.A.clone();d&&_.Wa(d,function(a,b){f.set(b,a)});d=_.ve(f.M(),Oe);c=_.k.FormData&&a instanceof _.k.FormData;!_.qe(_.Le,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.I&&(this.a.responseType=this.I);"withCredentials"in this.a&&(this.a.withCredentials=this.aa);try{Pe(this),0<this.v&&((this.w=Qe(this.a))?(this.a.timeout=this.v,this.a.ontimeout=(0,_.q)(this.K,this)):this.g=_.re(this.K,this.v,this)),this.f=!0,this.a.send(a),this.f=!1}catch(g){Ne(this)}};var Qe=function(a){return _.D&&_.gb(9)&&_.ka(a.timeout)&&_.n(a.ontimeout)},Oe=function(a){return"content-type"==a.toLowerCase()};
_.Je.prototype.K=function(){"undefined"!=typeof _.aa&&this.a&&(this.e=8,_.O(this,"timeout"),_.Re(this,8))};Ne=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.e=5;Se(a);Te(a)};Se=function(a){a.l||(a.l=!0,_.O(a,"complete"),_.O(a,"error"))};_.Re=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.e=b||7,_.O(a,"complete"),_.O(a,"abort"),Te(a))};_.Je.prototype.n=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Te(this,!0));_.Je.t.n.call(this)};
_.Je.prototype.J=function(){this.C||(this.p||this.f||this.c?Ue(this):this.W())};_.Je.prototype.W=function(){Ue(this)};Ue=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.h[1]||4!=(a.a?a.a.readyState:0)||2!=_.Ve(a)))if(a.f&&4==(a.a?a.a.readyState:0))_.re(a.J,0,a);else if(_.O(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.We(a)?(_.O(a,"complete"),_.O(a,"success")):(a.e=6,Se(a))}finally{Te(a)}}};
Te=function(a,b){if(a.a){Pe(a);var c=a.a,d=a.h[0]?_.oa:null;a.a=null;a.h=null;b||_.O(a,"ready");try{c.onreadystatechange=d}catch(e){}}};Pe=function(a){a.a&&a.w&&(a.a.ontimeout=null);_.ka(a.g)&&(_.se(a.g),a.g=null)};
_.We=function(a){var b=_.Ve(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=_.rb(String(a.q))[1]||null,!a&&window.self.location&&(a=window.self.location.protocol,a=a.substr(0,a.length-1)),b=!Ke.test(a?a.toLowerCase():"");c=b}return c};_.Ve=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};_.Xe=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
_.Ye=function(a){_.x(this,a,"h_icr",null)};_.p(_.Ye,_.w);_.z("h_icr",_.Ye);_.Ze=function(a){_.x(this,a,"h_cs",null)};_.p(_.Ze,_.w);_.z("h_cs",_.Ze);_.Ze.prototype.getState=function(){return _.y(this,1)};_.$e=new _.L("HwdKC");
}catch(e){_._DumpException(e)}
try{
_.af=function(){return window.chrome.runtime.getURL("feedbackdialog.html")};
}catch(e){_._DumpException(e)}
try{
_.k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_description:{message:"Always stay connected with the new desktop app for Hangouts on ChromeOS and Windows."},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},
chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},chrome_app_signin_button:{message:"Sign in"},chrome_app_outdated_title:{message:"Update your Hangouts Chrome app"},chrome_app_outdated_detail:{message:"This app is out of date. There's a newer version available."},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_title_2:{message:"Do you want to quit Hangouts?"},chrome_app_exit_detail:{message:"You will not receive new messages or calls on this device"},
chrome_app_exit_detail_2:{message:"You can also choose to minimize it and continue to receive messages and calls."},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"},chrome_app_exit_minimize:{message:"Minimize"},chrome_app_osx_warning_message:{message:"Hangouts Chrome app is not fully supported on Mac OSX."},chrome_app_osx_warning_ack:{message:"OK, GOT IT"}};

}catch(e){_._DumpException(e)}
try{
var bf=function(a,b){var c,d,e,f;c=window.document;c=b||c;if(c.querySelectorAll&&c.querySelector&&a)return c.querySelectorAll(""+(a?"."+a:""));if(a&&c.getElementsByClassName){var g=c.getElementsByClassName(a);return g}g=c.getElementsByTagName("*");if(a){f={};for(d=e=0;c=g[d];d++){var l=c.className;"function"==typeof l.split&&_.qe(l.split(/\s+/),a)&&(f[e++]=c)}f.length=e;return f}return g},cf=function(a){return a instanceof _.ie?a.clone():new _.ie(a,void 0)},df=function(a){_.x(this,a,0,null)};
_.p(df,_.w);var ef=function(a){_.x(this,a,0,null)};_.p(ef,_.w);var ff=function(a){_.x(this,a,0,null)};_.p(ff,_.w);var gf=function(a){_.x(this,a,0,null)};_.p(gf,_.w);
var hf=/[?&]($|#)/,jf=/#|$/,kf=function(a,b,c,d){for(var e=c.length;0<=(b=a.indexOf(c,b))&&b<d;){var f=a.charCodeAt(b-1);if(38==f||63==f)if(f=a.charCodeAt(b+e),!f||61==f||38==f||35==f)return b;b+=e+1}return-1},lf=function(a){if(a&&"number"==typeof a.length){if(_.ia(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.ja(a))return"function"==typeof a.item}return!1},mf={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",
role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},nf=/[\x00&<>"']/,of=/\x00/g,pf=/'/g,qf=/"/g,rf=/>/g,sf=/</g,tf=/&/g,uf=function(a,b,c){function d(c){c&&b.appendChild(_.t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.la(f)||_.ia(f)&&0<f.nodeType?d(f):(0,_.v)(lf(f)?_.Ud(f):f,d)}},vf=function(a,b){_.Ca(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in mf?a.setAttribute(mf[d],b):0==d.lastIndexOf("aria-",
0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},wf=function(a){if(!nf.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(tf,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(sf,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(rf,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(qf,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(pf,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(of,"&#0;"));return a},xf={LOADING:0,sc:1,ud:2,vd:3,ERROR:4,LOADED:5,rc:6},yf=function(a,b,c){for(var d=a.search(jf),e=0,f,g=[];0<=(f=kf(a,
e,b,d));)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.substr(e));a=[g.join("").replace(hf,"$1"),"&",b];null!=c&&a.push("=",(0,window.encodeURIComponent)(String(c)));a[1]&&(c=a[0],b=c.indexOf("#"),0<=b&&(a.push(c.substr(b)),a[0]=c=c.substr(0,b)),b=c.indexOf("?"),0>b?a[1]="?":b==c.length-1&&(a[1]=void 0));return a.join("")},zf=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},Af=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,
Bf=function(a){_.J.call(this);this.e=a;this.b=xf.LOADING;this.a=!1;this.c=new _.I(this);_.G(this,this.c);this.c.listen(this.e.ta(),"h_cs",this.f)};_.p(Bf,_.J);Bf.prototype.getState=function(){return this.b};Bf.prototype.h=function(){return this.a};Bf.prototype.f=function(a){a=new _.Ze(a.ab);var b=a.getState();null!=b&&this.b!=b&&(this.b=b,_.O(this,"d"));a=_.y(a,2);null!=a&&this.a!=a&&(this.a=a,_.O(this,"c"))};
var Cf=function(a){(a?a:function(){}).Jc=!0},Df=function(a,b,c){var d=arguments,e=window.document,f=d[0],g=d[1];if(!_.lb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',wf(g.name),'"');if(g.type){f.push(' type="',wf(g.type),'"');var l={};_.Md(l,g);delete l.type;g=l}f.push(">");f=f.join("")}f=e.createElement(f);g&&(_.t(g)?f.className=g:_.ma(g)?f.className=g.join(" "):vf(f,g));2<d.length&&uf(e,f,d);return f},Ef=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]: c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=bf(a,b)[0];return d||null};
var Ff=function(a){this.a=a;_.D||(delete this.a.lpu,delete this.a.ppu)},Gf=["cn","tp"],Hf=function(a,b){var c=null,d;if(_.ja(window.document.postMessage)||_.ja(window.postMessage)||_.D&&window.postMessage)d=1;else if(_.Ya)d=2;else{if(c=_.D){c=!1;try{d=window.opener,window.opener={},c=_.nb(window,"opener"),window.opener=d}catch(e){}}d=c?6:4}c=d;d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new Ff(d)};_.ga("GTalk_IFrameChannelConfig.build",Hf);
var If=function(){if(Ef("talk_loading_msg")){var a=Ef("talk_loading_msg_error");a&&_.vd(a)}},Jf=function(a){var b=Ef("talk_loading_msg");if(b){If();var c=window.document.createElement("DIV");vf(c,{"class":"talk_loading_msg_error",style:"margin: 12px 8px; font-size: 10px"});var d=window.document.createElement("DIV");a="Errors: "+a.join(", ");if("textContent"in d)d.textContent=a;else if(3==d.nodeType)d.data=a;else if(d.firstChild&&3==d.firstChild.nodeType){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild); d.firstChild.data=a}else zf(d),d.appendChild((9==d.nodeType?d:d.ownerDocument||d.document).createTextNode(String(a)));c.appendChild(d);b.appendChild(c)}};
var Kf=function(){};_.p(Kf,_.we);Kf.prototype.b=function(a){return a};Cf(Kf.prototype.b);Kf.prototype.c=function(){return!0};Cf(Kf.prototype.c);var Lf=function(a){_.x(this,a,0,null)};_.p(Lf,_.w);var Mf=function(a,b){var c=new Lf;_.M(c,1,b);_.M(c,2,a);return c},Nf=Mf("?",0),Of=Mf("q",1),Pf=Mf("<",2),Qf=Mf(">",3),Rf=Mf("~",4),Sf=Mf("s",5),Tf={e:Nf,k:Of,g:Pf,h:Qf,f:Rf,l:Sf};var Uf=function(a){_.x(this,a,"ci:dc",null)};_.p(Uf,_.w);_.z("ci:dc",Uf);var Vf=function(a){_.x(this,a,"ci:ec",null)};_.p(Vf,_.w);_.z("ci:ec",Vf);var Wf=function(a){return null!=_.y(a,2)?_.y(a,2):!1};var Xf=function(a){this.a=a},Yf=/\s*;\s*/;_.h=Xf.prototype;_.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("v`"+a);if(/[;\r\n]/.test(b))throw Error("w`"+b);_.n(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.m)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.h.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(Yf),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.h.remove=function(a,b,c){var d=_.n(this.get(a));this.set(a,"",0,b,c);return d};_.h.M=function(){return Zf(this).keys};_.h.B=function(){return Zf(this).values};_.h.P=function(){return!this.a.cookie};_.h.V=function(){return this.a.cookie?(this.a.cookie||"").split(Yf).length:0};
_.h.clear=function(){for(var a=Zf(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};var Zf=function(a){a=(a.a.cookie||"").split(Yf);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var $f=function(a,b,c){_.Ce(this);var d=this.qb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(0==d.lastIndexOf("https://talkgadget.google.com/talkgadget/",0)){var e=(new Xf(window.document)).get("WCSDBG",""),e=e.split(";")[0],e=e.split("|")[0],f=["plus.google.com"],g=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<e.length&&!_.qe(f,e)&&g.test(e)&&(d=cf(d),d=cf("https://"+e+d.N).toString())}this.ca=d;this.c=c||new Vf;a.notificationsOnly&&_.M(this.c,1,!0);this.b="0";null!=a.authUser?
this.b=a.authUser:(c=_.oe(new _.ie(window.location.href),"authuser"),null!=c&&(this.b=c));this.j=a.clientUrl||"notifierclient";c=_.oe(cf(this.j),"authuser");null!=c&&(this.b=c);this.g=a.propertyName||"Google Talk";this.l=a.cssUrl;this.locale=a.locale;this.f=a.debug;this.Lb=a.userJid;this.Ib=a.uiVersion;this.qc=null!=a.rosterExpanded?a.rosterExpanded:!0;this.L=a.hostLogMinValue;this.Qa=a.hideChat;this.xc=a.refresh;this.A=a.hideProfileCard;this.K=a.hideStatusMsgs;this.J=a.hideRosterOptions;this.I=a.hideRecentConversations;
this.w=a.hideOTR;this.uc=a.hostServerMessageCallback||!1;this.W=a.isCentralRoster;this.wc=a.isFullFrame||!1;this.Ac=a.rosterClass||"talk_roster";this.Ca=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.e=a.parentToken;this.zc=b||!1;_.n(a.isRtl)||Af.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var l in Tf)b.push(Tf[l].F)}this.q=
a.entityId;this.Jb=a.useQuasarPanels||!1;this.Gb=a.silent||!1;this.vc=a.ignoreCentralRoster||!1;this.yc=a.lazy||!1;this.tc=a.handleProfileLinks||!1;this.S=a.hostSettings;this.h=a.screen;this.p=a.docsConfig;this.aa=a.jsmode;this.Ba=a.moleWidth;this.Aa=a.moleHeight;this.za=a.minimizedMoleHeight||36;this.Bc=a.derp;this.Hb=window.location.protocol+"//"+window.location.host;this.v=a.optOutAllowed;this.u=a.legacyTalkSignedIn;this.Kb=a.useSpareMole;this.k=a.conversationId};Kf.t||_.p(Kf,_.we);$f.ia=Kf;
var ag=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp"}};
var bg=function(a,b,c,d,e){_.E.call(this);this.a=a;this.b=d||window.document;this.c=new _.I(this);_.G(this,this.c);var f=_.Ka;d=new _.ie(a.ca+a.j);Wf(a.c)||(_.R(d,"ts","0"),_.R(d,"re",a.qc),_.R(d,"ref",a.xc));_.R(d,"client","sm");_.R(d,"prop",a.g);_.R(d,"nav","true");_.R(d,"fid",a.a);a.f&&_.R(d,"debug",a.f);_.R(d,"os",_.ab);_.R(d,"stime",c);a.Qa&&_.R(d,"hc",a.Qa);for(c=0;c<Gf.length;++c);b=_.Nd(b.a);_.R(d,"xpc",b);_.R(d,"ec",_.Nd(a.c.F));a.h&&_.R(d,"screen",a.h);-1!=f.indexOf("MSIE")&&_.R(d,"ua",
f);a.e&&_.R(d,"pvt",a.e);a.uc&&_.R(d,"hsmc","true");_.n(a.L)&&_.R(d,"logl",a.L);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.R(d,"href",b.join("?")));b=new _.ie(window.location.href);"false"==_.oe(b,"uacheck")&&_.R(d,"uacheck",!1);(f=a.aa)&&_.R(d,"jsmode",f);(f=_.oe(b,"cssmode"))&&_.R(d,"cssmode",f);(f=_.oe(b,"convid"))&&_.R(d,"convid",f);(f=b.a.B("convp"))&&_.ne(d,"convp",f);(f=_.oe(b,"smexp"))&&_.R(d,"smexp",f);f=b.a.B("mods");
a.yc&&f.push("lazy");e&&(f=_.Vd(f,e));0<f.length&&_.R(d,"mods",f.join(","));if(!a.ca||0>a.ca.indexOf("/u/"))(e=_.oe(b,"authuser"))?_.R(d,"authuser",e):null!=a.b&&_.R(d,"authuser",a.b);e=_.oe(b,"eid");/^[\s\xa0]*$/.test(null==e?"":String(e))||_.R(d,"eid",e);e=this.a.q;/^[\s\xa0]*$/.test(null==e?"":String(e))||_.R(d,"eid",this.a.q);null!=this.a.position&&_.R(d,"pos",this.a.position);_.n(a.Ib)&&_.R(d,"uiv",this.a.Ib);a.l&&_.R(d,"css",a.l);e=a.locale||_.oe(b,"hl");null!=e&&_.R(d,"hl",e);_.n(a.Lb)&&_.R(d,
"uj",a.Lb);null!=a.A&&_.R(d,"hpc",a.A);null!=a.K&&_.R(d,"hsm",a.K);null!=a.J&&_.R(d,"hro",a.J);null!=a.I&&_.R(d,"hrc",a.I);null!=a.w&&_.R(d,"hotr",a.w);null!=a.W&&_.R(d,"pop",a.W);a.zc&&_.R(d,"pal","1");null!=a.Jb&&_.R(d,"uqp",a.Jb);null!=a.v&&_.R(d,"gooa",a.v);null!=a.u&&_.R(d,"gltsi",a.u);null!=a.Kb&&_.R(d,"gusm",a.Kb);null!=a.Gb&&_.R(d,"sl",a.Gb);a.vc&&_.R(d,"icr","1");a.tc&&_.R(d,"hpl","1");a.S&&_.R(d,"hs",a.S);a.p&&_.R(d,"dc",_.Nd(a.p.F));null!=a.Ba&&_.R(d,"molew",a.Ba);null!=a.Aa&&_.R(d,"moleh",
a.Aa);null!=a.za&&_.R(d,"mmoleh",a.za);a.Bc&&_.R(d,"derp","1");null!=a.Hb&&_.R(d,"two",a.Hb);null!=a.k&&_.R(d,"convid",a.k);_.R(d,"host","1");_.R(d,"zx",_.he());this.e=d.toString()};_.p(bg,_.E);
var cg=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Ac,a.b.body.appendChild(e));a=(0,_.q)(function(){var a="";this.a.wc||(a="height:400px");var b=this.b.createElement("iframe");vf(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a});Ef("talk_loading_msg",e)||zf(e);e.appendChild(b);var l=this.b.getElementById(this.a.a);_.Pd(this.c,l,["load","error"],function(){l.contentWindow.postMessage("AllowFrame: Chat","*");d()});l.src= this.e.toString();c()},a);window.setTimeout(a,0)};
var dg=function(a){_.H.call(this,a[0]);this.ab=a};_.p(dg,_.H);var eg=function(a){_.x(this,a,"h_ccf",null)};_.p(eg,_.w);_.z("h_ccf",eg);var fg=function(a){_.x(this,a,"h_rtp",null)};_.p(fg,_.w);_.z("h_rtp",fg);var gg=function(a,b){_.E.call(this);this.I=(0,_.m)();this.A=a;this.document=b||window.document;this.a=new $f(a,!0,a.endpointConfig);this.g=[];this.q=new _.J;this.f=null};_.p(gg,_.E);gg.prototype.n=function(){gg.t.n.call(this);_.se(this.f);this.b&&this.l&&this.b.parentNode.removeEventListener("DOMAttrModified",this.l,!0)};gg.prototype.e=function(a,b){this.c?this.c[a]&&this.c[a].apply(this.c,Array.prototype.slice.call(arguments,1)):this.g.push(arguments)};
gg.prototype.h=function(){var a=this.Yb().GTalkNotifier;if(a){var b=_.te(this.A);b.endpointConfig=this.a.c.F;this.c=new a(b,!0);for(a=0;a<this.g.length;a++)this.e.apply(this,this.g[a]);this.g=[];a=(0,_.q)(this.onMessage,this);this.e("_addClientMessageCallback",a);this.e("_addHostBundleMessageCallback",a)}};gg.prototype.onMessage=function(a){switch(a[0]){case "h_ccf":var b=new eg(a);_.y(b,1)}_.O(this.q,new dg(a))};var hg=function(a,b){a.e("_h",b.F)};_.h=gg.prototype;
_.h.sendMessage=function(a){hg(this,a)};_.h.ta=function(){return this.q};_.h.Yb=function(){return this.document.parentWindow||this.document.defaultView};_.h.Sc=function(a,b){if(b.target==a&&("style"==b.attrName||"class"==b.attrName)){var c=new fg;hg(this,c)}};_.h.Tc=function(){Ef("talk_loading_msg",this.document.getElementById(this.a.Ca))&&(this.document.getElementById(this.a.a).style.display="none")};
var ig=function(a){var b=a.a.ca+"host-js",b=yf(b,"prop",a.a.g),c=a.a.aa;c&&(b=yf(b,"jsmode",c));Wf(a.a.c)&&(b=yf(b,"b","1"));var b=yf(b,"zx",_.he()),d=(0,_.q)(a.h,a),e=Df("script",{type:"text/javascript",src:b}),f=!1;e.onload=e.onreadystatechange=function(){f||e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(f=!0,d())};e.onerror=(0,_.q)(a.u,a,e);a.f&&(_.se(a.f),a.f=null);a.f=_.re((0,_.q)(function(){null!=this.c||this.v(e)},a),25E3);a.document.body.appendChild(e)};gg.prototype.u=function(){}; gg.prototype.v=function(){};
var jg=function(a){if(a.classList)return a.classList;a=a.className;return _.t(a)&&a.match(/\S+/g)||[]},kg=function(a){return a.classList?a.classList.contains("talk_network_warning"):_.qe(jg(a),"talk_network_warning")},lg=function(a){a.classList?a.classList.remove("talk_network_warning"):kg(a)&&(a.className=(0,_.wa)(jg(a),function(a){return"talk_network_warning"!=a}).join(" "))};
var mg=function(a,b){this.b=a;this.c=b;this.a=a};mg.prototype.reset=function(){this.a=this.b};mg.prototype.G=function(){return this.a};var ng=function(a){a.a=Math.min(a.c,2*a.a)};var og=function(a,b,c){var d={},e;e=null!=_.y(a,1)?_.y(a,1):"talkgadget.google.com";var f="";0>e.indexOf("://")&&(f="https://",0<=e.indexOf(":")&&23!=_.y(a,2)&&27!=_.y(a,2)&&(f="http://"));d.clientBaseUrl=f+e+"/talkgadget/_/";e=null!=_.y(a,8)?_.y(a,8):"0";d.authUser=e;d.clientUrl="chat";d.propertyName=ag(_.y(a,2));d.locale=_.y(a,4);d.hideProfileCard=!0;d.parentToken=_.y(a,3);e=null!=_.y(a,6)?_.y(a,6):!1;d.isRtl=e;e=null!=_.y(a,7)?_.y(a,7):!1;d.lazy=e;d.entityId=_.y(a,9);d.hostSettings=_.y(a,5);d.jsmode=
_.y(a,11);e=null!=_.y(a,13)?_.y(a,13):!1;d.isFullFrame=e;e=null!=_.y(a,12)?_.y(a,12):"talk_roster";d.rosterId=e;e=null!=_.y(a,15)?_.y(a,15):"gtn-roster-iframe-id-b";d.rosterIframeIdB=e;e=null!=_.y(a,16)?_.y(a,16):!1;d.derp=!!e;e=_.P(a,df,14);null!=e&&(f=null!=_.y(e,1)?_.y(e,1):!1,d.isCentralRoster=f,e=null!=_.y(e,2)?_.y(e,2):!1,d.useQuasarPanels=e);e=_.P(a,gf,10);null!=e&&(d.moleManagerLeftMargin=_.y(e,1),d.moleManagerMiddleMargin=_.y(e,2),d.moleManagerRightMargin=_.y(e,3),d.moleManagerNoMoleAreaMargin=
_.y(e,4),d.moleManagerBoundingElementId=_.y(e,5),d.moleWidth=_.y(e,6),d.moleHeight=_.y(e,7),d.minimizedMoleHeight=_.y(e,8));e=_.P(a,ff,18);null!=e&&(f=null!=_.y(e,1)?_.y(e,1):!0,d.optOutAllowed=f,f=_.P(e,ef,3),null!=f&&(f=null!=_.y(f,1)?_.y(f,1):!0,d.legacyTalkSignedIn=f),e=_.y(e,4),null!=e&&(d.useSpareMole=e));d.uiVersion=2;d.hideStatusMsgs=!0;d.hideRecentConversations=!0;e=new Vf;_.M(e,2,!0);_.M(e,1,!0);_.M(e,3,!1);d.endpointConfig=e;e=null!=_.y(a,17)?_.y(a,17):!1;d.ignoreAutomatedRoster=e;d.conversationId=
a.Z();d.hostCallback=c;gg.call(this,d,b);this.p=new mg(5E3,3E5);this.w=null};_.p(og,gg);var pg=function(a,b){var c=1+.5*Math.random();a.w=_.re(function(){null==this.c&&(_.pe(this.document.body,b)&&this.document.body.removeChild(b),ig(this))},a.p.G()*c,a);ng(a.p)};og.prototype.v=function(a){Jf(["301"]);pg(this,a)};
og.prototype.u=function(a){var b=Ef("talk_loading_msg",this.document.body);b&&(b.classList?b.classList.add("talk_network_warning"):kg(b)||(b.className+=0<b.className.length?" talk_network_warning":"talk_network_warning"));Jf(["302"]);pg(this,a)};og.prototype.h=function(){og.t.h.call(this);var a=Ef("talk_loading_msg",this.document.body);a&&lg(a);If()};og.prototype.n=function(){og.t.n.call(this);_.se(this.w)};
var qg=function(a){_.J.call(this);this.c=a?a:null;this.a=null;this.e=!1;this.b=[];this.f=(0,_.q)(this.Dc,this);this.g=(0,_.q)(this.Mb,this);this.h=null};_.p(qg,_.J);var rg=function(a){_.H.call(this,"message");this.message=a};_.p(rg,_.H);_.h=qg.prototype;_.h.n=function(){qg.t.n.call(this);_.se(this.h);this.Mb(!0);for(var a=0;a<this.b.length;++a)_.F(this.b[a]);delete this.b;delete this.f;delete this.g};
_.h.sendMessage=function(a){if(null==a||null==a.message)return!1;_.Qc(a,this.c,"p");this.a&&this.e?this.a.postMessage(a.message()):this.b.push(a);return!0};_.h.connect=function(){if(null==this.c)return!1;try{if(this.a=window.chrome.runtime.connect({name:this.c}),null==this.a)return!1}catch(a){return!1}this.e=!0;this.a.onMessage.addListener(this.f);this.a.onDisconnect.addListener(this.g);for(var b=this.b.shift();null!=b;)_.Qc(b,this.c,"p"),this.a.postMessage(b.message()),b=this.b.shift();return!0};
_.h.Dc=function(a){_.O(this,new rg(_.Pc(new _.Oc,a)))};_.h.Mb=function(a){this.a&&(this.a.onMessage.removeListener(this.f),this.a.onDisconnect.removeListener(this.g),this.a.disconnect(),delete this.a);this.e=!1;a||(this.h=_.re(this.nd,5E3,this))};_.h.nd=function(){this.connect()?_.O(this,{type:"reconnected"}):_.O(this,{type:"disconnected"})};
var tg=function(a){_.x(this,a,"h_exts",sg)};_.p(tg,_.w);var sg=[2];_.z("h_exts",tg);var ug=function(){_.E.call(this);this.b=" "};_.p(ug,_.E);var vg=function(a,b,c){a.a=c;b=new _.ie(b);b=_.me(b,new _.ie("/talkgadget/_/extension-start"));a=(0,_.q)(a.c,a);c=new _.Je;_.Me.push(c);a&&c.listen("complete",a);c.U.add("ready",c.S,!0,void 0,void 0);c.send(b,void 0,void 0,void 0)};ug.prototype.c=function(a){if(!this.C){this.b="";if(_.We(a.target))try{var b=JSON.parse(_.Xe(a.target)),c=new tg(b);this.b=_.y(c,1)||""}catch(d){}this.a&&(this.a(),this.a=null)}};
var wg=function(a){_.x(this,a,"h_cp",null)};_.p(wg,_.w);_.z("h_cp",wg);var xg=function(a){_.x(this,a,"rbc_d",null)};_.p(xg,_.w);_.z("rbc_d",xg);xg.prototype.setTitle=function(a){_.M(this,1,a)};var zg=function(a){_.x(this,a,"h_cd",yg)};_.p(zg,_.w);var yg=[1,4,5];_.z("h_cd",zg);zg.prototype.Z=function(){return _.y(this,2)};var Ag=function(a){_.x(this,a,"h_hn",null)};_.p(Ag,_.w);_.z("h_hn",Ag);var Bg=function(a){_.x(this,a,"h_hs",null)};_.p(Bg,_.w);_.z("h_hs",Bg);var Dg=function(a){_.x(this,a,"h_jm",Cg)};_.p(Dg,_.w);var Cg=[2];_.z("h_jm",Dg);var Eg=function(a){_.x(this,a,"h_oc",null)};_.p(Eg,_.w);_.z("h_oc",Eg);var Fg=function(a){_.x(this,a,"h_opc",null)};_.p(Fg,_.w);_.z("h_opc",Fg);var Gg=function(a){_.x(this,a,"h_ogc",null)};_.p(Gg,_.w);_.z("h_ogc",Gg);var Hg=function(a){_.x(this,a,"h_sc",null)};_.p(Hg,_.w);_.z("h_sc",Hg);var Jg=function(a){_.x(this,a,"h_ssc",Ig)};_.p(Jg,_.w);var Ig=[5];_.z("h_ssc",Jg);var Lg=function(a){_.x(this,a,"h_sm",Kg)};_.p(Lg,_.w);var Kg=[1,3];_.z("h_sm",Lg);var Mg=function(a){_.x(this,a,"h_po",null)};_.p(Mg,_.w);_.z("h_po",Mg);var Ng=function(a){_.J.call(this);this.a=a};_.p(Ng,_.J);var Og=new _.L("O9EQob");var Pg=function(a){_.x(this,a,"capi:f_cfr",null)};_.p(Pg,_.w);_.z("capi:f_cfr",Pg);var Qg=function(a){_.x(this,a,"capi:f_cvr",null)};_.p(Qg,_.w);_.z("capi:f_cvr",Qg);var Rg=function(a){_.x(this,a,"capi:f_vsm",null)};_.p(Rg,_.w);_.z("capi:f_vsm",Rg);var Sg=function(a){_.x(this,a,"capi:f_ccr",null)};_.p(Sg,_.w);_.z("capi:f_ccr",Sg);var Tg=function(a){_.x(this,a,"capi:f_csm",null)};_.p(Tg,_.w);_.z("capi:f_csm",Tg);var Ug=function(a){_.x(this,a,0,null)};_.p(Ug,_.w);
var Vg=function(a){_.x(this,a,"capi:f_var",null)};_.p(Vg,_.w);_.z("capi:f_var",Vg);Vg.prototype.getState=function(){return _.P(this,Ug,1)};var Wg=function(a){_.x(this,a,"capi:f_van",null)};_.p(Wg,_.w);_.z("capi:f_van",Wg);Wg.prototype.getState=function(){return _.P(this,Ug,1)};var Xg=function(a){_.x(this,a,0,null)};_.p(Xg,_.w);var Yg=function(a){_.x(this,a,"capi:f_vcr",null)};_.p(Yg,_.w);_.z("capi:f_vcr",Yg);Yg.prototype.getState=function(){return _.P(this,Xg,1)};
var Zg=function(a){_.x(this,a,"capi:f_vcn",null)};_.p(Zg,_.w);_.z("capi:f_vcn",Zg);Zg.prototype.getState=function(){return _.P(this,Xg,1)};var $g=function(a){_.x(this,a,0,null)};_.p($g,_.w);var ah=function(a){_.x(this,a,"capi:f_vcor",null)};_.p(ah,_.w);_.z("capi:f_vcor",ah);ah.prototype.getState=function(){return _.P(this,$g,1)};var bh=function(a){_.x(this,a,"capi:f_vcon",null)};_.p(bh,_.w);_.z("capi:f_vcon",bh);bh.prototype.getState=function(){return _.P(this,$g,1)};
var ch=function(a){_.x(this,a,0,null)};_.p(ch,_.w);var dh=function(a){_.x(this,a,"capi:f_vfr",null)};_.p(dh,_.w);_.z("capi:f_vfr",dh);dh.prototype.getState=function(){return _.P(this,ch,1)};var eh=function(a){_.x(this,a,"capi:f_vfn",null)};_.p(eh,_.w);_.z("capi:f_vfn",eh);eh.prototype.getState=function(){return _.P(this,ch,1)};var fh=function(a){_.x(this,a,0,null)};_.p(fh,_.w);var gh=function(a){_.x(this,a,"capi:f_vmr",null)};_.p(gh,_.w);_.z("capi:f_vmr",gh);
gh.prototype.getState=function(){return _.P(this,fh,1)};var hh=function(a){_.x(this,a,"capi:f_vmn",null)};_.p(hh,_.w);_.z("capi:f_vmn",hh);hh.prototype.getState=function(){return _.P(this,fh,1)};var ih=function(a){_.x(this,a,0,null)};_.p(ih,_.w);var jh=function(a){_.x(this,a,"capi:f_vpr",null)};_.p(jh,_.w);_.z("capi:f_vpr",jh);jh.prototype.getState=function(){return _.P(this,ih,1)};var kh=function(a){_.x(this,a,"capi:f_vpn",null)};_.p(kh,_.w);_.z("capi:f_vpn",kh);
kh.prototype.getState=function(){return _.P(this,ih,1)};var lh=function(a){_.x(this,a,"capi:f_vsr",null)};_.p(lh,_.w);_.z("capi:f_vsr",lh);var mh=function(a){_.x(this,a,"capi:f_vsn",null)};_.p(mh,_.w);_.z("capi:f_vsn",mh);var nh=function(a){_.x(this,a,"capi:f_vtr",null)};_.p(nh,_.w);_.z("capi:f_vtr",nh);nh.prototype.setTitle=function(a){_.Qd(this,1,a)};var oh=function(a){_.x(this,a,"capi:f_vtn",null)};_.p(oh,_.w);_.z("capi:f_vtn",oh);oh.prototype.setTitle=function(a){_.Qd(this,1,a)};
var ph=function(a){_.x(this,a,0,null)};_.p(ph,_.w);var qh=function(a){_.x(this,a,"capi:f_vvr",null)};_.p(qh,_.w);_.z("capi:f_vvr",qh);qh.prototype.getState=function(){return _.P(this,ph,1)};var rh=function(a){_.x(this,a,"capi:f_vvn",null)};_.p(rh,_.w);_.z("capi:f_vvn",rh);rh.prototype.getState=function(){return _.P(this,ph,1)};var sh=function(a){_.x(this,a,0,null)};_.p(sh,_.w);var th=function(a){_.x(this,a,"capi:f_uvor",null)};_.p(th,_.w);_.z("capi:f_uvor",th);
var uh=function(a){_.x(this,a,"capi:f_uvon",null)};_.p(uh,_.w);_.z("capi:f_uvon",uh);var vh=function(a){_.x(this,a,0,null)};_.p(vh,_.w);var wh=function(a){_.x(this,a,"capi:f_sp",null)};_.p(wh,_.w);_.z("capi:f_sp",wh);wh.prototype.getState=function(){return _.P(this,vh,1)};var xh=function(a){_.x(this,a,"capi:f_spn",null)};_.p(xh,_.w);_.z("capi:f_spn",xh);xh.prototype.getState=function(){return _.P(this,sh,1)};
var yh=function(a){_.x(this,a,"uvc",null)};_.p(yh,_.w);_.z("uvc",yh);var zh=function(a){_.x(this,a,"capi:clstup",null)};_.p(zh,_.w);_.z("capi:clstup",zh);var Ah=function(a){_.x(this,a,"capi:r_clre",null)};_.p(Ah,_.w);_.z("capi:r_clre",Ah);var Bh=function(a){_.x(this,a,"capi:r_rrst",null)};_.p(Bh,_.w);_.z("capi:r_rrst",Bh);var Ch=function(a){_.x(this,a,"capi:r_rers",null)};_.p(Ch,_.w);_.z("capi:r_rers",Ch);var Dh=function(a){_.x(this,a,"capi:r_recl",null)};_.p(Dh,_.w);_.z("capi:r_recl",Dh);var Eh=function(a){_.x(this,a,"capi:r_rstr",null)};_.p(Eh,_.w); _.z("capi:r_rstr",Eh);
var Fh=new _.L("nED8Yb"),Gh=new _.L("xclgJb");var Hh=function(a){_.x(this,a,"h_ec",null)};_.p(Hh,_.w);_.z("h_ec",Hh);var Ih=function(a){_.x(this,a,"h_fr",null)};_.p(Ih,_.w);_.z("h_fr",Ih);var Jh=function(a){_.x(this,a,"capii_c_cel",null)};_.p(Jh,_.w);_.z("capii_c_cel",Jh);var Kh=function(a){_.x(this,a,"capi:rfc",null)};_.p(Kh,_.w);_.z("capi:rfc",Kh);var Lh=function(a){_.x(this,a,"capii_c_ucmc",null)};_.p(Lh,_.w);_.z("capii_c_ucmc",Lh);var Mh=function(a){_.x(this,a,"capii_c_rc",null)};_.p(Mh,_.w);_.z("capii_c_rc",Mh);Mh.prototype.Z=function(){return _.y(this,1)};
var Nh=function(a){_.J.call(this);this.c=a.get(Fh);this.a=this.f=0;this.e=this.b=!1;a=new _.I(this);_.G(this,a);a.listen(this.c.ta(),"capii_c_ucmc",this.g);this.c.sendMessage(new Lh)};_.p(Nh,_.J);Nh.prototype.g=function(a){a=new Lh(a.ab);this.b||(this.b=!0,this.e&&(_.M(a,5,!0),this.e=!1));var b=this.f!=_.y(a,1);this.f=Number(_.y(a,1));var c=this.a!=_.y(a,2);this.a=Number(_.y(a,2));_.y(a,5)?_.O(this,"h"):(b&&_.O(this,"j"),c&&_.O(this,"i"))};
var Oh=function(a){_.x(this,a,"h_rha",null)};_.p(Oh,_.w);_.z("h_rha",Oh);var Ph=function(a){_.x(this,a,"h_ssf",null)};_.p(Ph,_.w);_.z("h_ssf",Ph);var Qh=function(a,b){_.E.call(this);this.a=new _.I(this);_.G(this,this.a);this.a.listen(a.ta(),"h_ssf",function(a){a=new Ph(a.ab);a=_.y(a,1);var c;if(null!=a&&JSON&&JSON.parse)try{c=JSON.parse(a)}catch(f){}b(c)});var c=new Oh;_.M(c,1,1);hg(a,c)};_.p(Qh,_.E);
var Rh=function(a){_.x(this,a,"h_ext",null)};_.p(Rh,_.w);_.z("h_ext",Rh);var Sh=function(a){_.x(this,a,"h_sru",null)};_.p(Sh,_.w);_.z("h_sru",Sh);var Vh=function(){_.I.call(this);this.b=new _.yd;_.G(this,this.b);this.l=this.f=this.k=this.a=null;this.q=_.Mc("quasar",""+(new Date).getTime());this.c=[];this.e=new qg(this.q);_.G(this,this.e);this.h=null;this.e.connect();_.Wb(this,this.e,"message",this.J,!0,this);this.p=new ug;_.G(this,this.p);this.listen(window,"unload",this.D);this.listen(window,"load",this.v);Th(this,(0,_.q)(function(){Uh(this,["onHostReady"],"extensionLibrary")},this))},Wh;_.p(Vh,_.I);var Th=function(a,b){null==a.c?b():a.c.push(b)};
Vh.prototype.v=function(){var a=new _.Xc(_.ad.ua().get("settings"));this.h=a.b[0];_.F(a);vg(this.p,this.h,(0,_.q)(function(){if(!this.C&&-1!=this.h.lastIndexOf("talkgadget/")){var a=new Vf;_.M(a,2,!0);var a=new _.Ub,c=this.p.b;if(c){_.M(a,3,c);var c=cf(this.h),d=c.R;null!=c.ea&&(d+=":"+c.ea);_.M(a,1,d);_.M(a,2,23);d=window.chrome.i18n.getMessage("@@ui_locale");_.M(a,4,d);_.M(a,13,!0);_.M(a,17,!0);c=_.oe(c,"jsmode");null!=c&&_.M(a,11,c);c=new df;_.M(c,2,!0);_.M(c,1,!0);_.Qd(a,14,c);a=new og(a,void 0,
(0,_.q)(this.A,this));_.t(void 0)&&(a.a.e=void 0);c=a.a;var e=a.a.ca,d=a.a.b,f=cf(e),g=f.N;if(0<=g.indexOf("/u/"))d=e;else{e=g.lastIndexOf("_/");if(0>e||e!=g.length-2)g+="_/";f.N="/u/"+d+g;d=f.toString()}c.ca=d;a.a.j=a.a.j.replace("notifierclient","chat");a.k||(c=Hf(a.a.ca,a.a.a),a.k=new bg(a.a,c,a.I,a.document,void 0),_.G(a,a.k));cg(a.k,a.a.Ca,(0,_.q)(a.Tc,a),(0,_.q)(a.e,a,"_rosterIframeLoaded"));_.Gc&&(a.b=a.document.createElement("IFRAME"),a.b.id="gth-talk-plugin-frame-id",a.b.name="gth-talk-plugin-frame-id",
a.b.src=a.a.ca+"blank",a.b.style.cssText="width: 0px; height: 0px; position: absolute; top: 0px; left: 0px; visibility:hidden;",a.document.documentElement.appendChild(a.b),a.l=(0,_.q)(a.Sc,a,a.b.parentNode),a.b.parentNode.addEventListener("DOMAttrModified",a.l,!0));ig(a);this.a=a;this.b.a(Fh,this.a);this.k=new Bf(this.a);this.b.a(_.$e,this.k);this.listen(this.k,"d",this.w);this.f=new Ng(this.a);this.b.a(Og,this.f);this.l=new Nh(this.b);this.b.a(Gh,this.l);this.listen(this.l,"i",this.u);this.u();a=
new Qh(this.a,(0,_.q)(this.K,this));_.G(this,a);this.listen(this.a.ta(),"h_sru",this.L)}else Uh(this,["changeDesktop",3],"desktopManager")}for(;this.c.length;)this.c.shift()();this.c=null},this))};Vh.prototype.A=function(a,b){if("extensionMessage"==a)if("__reload__"==b)window.chrome.runtime.reload();else{var c=new _.Oc;_.Pc(c,JSON.parse(b)||{});this.e.sendMessage(c)}};
Vh.prototype.w=function(){var a;switch(this.k.getState()){case xf.LOADING:a=2;break;case xf.sc:a=4;break;case xf.rc:a=3;break;default:return}Uh(this,["changeDesktop",a],"desktopManager")};
Vh.prototype.J=function(a){Th(this,(0,_.q)(function(){var b=a.message;switch(b.a){case "onSendHostMessage":var c=new Rh,b=b.content().toString();_.M(c,1,b);this.a&&this.a.sendMessage(c);break;case "onOpenConversation":var b=b.content()[0],c=this.f,d=new Eg;_.M(d,1,b);hg(c.a,d);d=new zg;_.M(d,1,[b]);b=new Fg;_.Qd(b,1,d);hg(c.a,b);break;case "h_icr":c=b.content()[0],this.f&&(b=this.f,d=new _.Ye,_.M(d,1,c),hg(b.a,d))}},this))};
var Uh=function(a,b,c){var d=new _.Oc;_.Qc(d,a.q,"p");_.Od(d,"","e");_.Sc(d,b);null!=c&&(d.g=c);_.Rc(d,""+(0,_.m)());a.e.sendMessage(d)};Vh.prototype.K=function(){var a=_.af();window.open(a)};Vh.prototype.L=function(a){a=new Sh(a.ab);Uh(this,["setRosterUrl",_.y(a,2)],"dataChannelManager")};Vh.prototype.u=function(){Uh(this,["setUnreadIndicator",!!this.l.a],"desktopManager")};
if(!_.n(Wh)||null==Wh||Wh.C)Wh=new Vh;
}catch(e){_._DumpException(e)}
}).call(this,this.default_datachannel);
// Google Inc.
