"use strict";this.default_feedback=this.default_feedback||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,da,ea;_.n=function(a){return void 0!==a};ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};da=function(a,b,c){return a.call.apply(a.bind,arguments)};
ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.t=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.wd=function(a,c,f){for(var g=Array(arguments.length-2),l=2;l<arguments.length;l++)g[l-2]=arguments[l];return b.prototype[c].apply(a,g)}};
_.ga=function(a,b){var c=a.split("."),d=_.k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.q=function(a,b,c){_.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return _.q.apply(null,arguments)};
_.ia=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ja=function(a){return"function"==ea(a)};_.ka=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.la=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ma=function(a){return"array"==ea(a)};_.oa=function(){};_.qa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.qa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}; _.p(_.qa,Error);_.qa.prototype.name="CustomError";
var ra=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ta=function(a,b){for(var c=0,d=ra(String(a)).split("."),e=ra(String(b)).split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var l=d[g]||"",r=e[g]||"",C=RegExp("(\\d*)(\\D*)","g"),N=RegExp("(\\d*)(\\D*)","g");do{var fa=C.exec(l)||["","",""],Q=N.exec(r)||["","",""];if(0==fa[0].length&&0==Q[0].length)break;c=sa(0==fa[1].length?0:(0,window.parseInt)(fa[1],10),0==Q[1].length?0:(0,window.parseInt)(Q[1], 10))||sa(0==fa[2].length,0==Q[2].length)||sa(fa[2],Q[2])}while(0==c)}return c},sa=function(a,b){return a<b?-1:a>b?1:0};
_.u=Array.prototype;_.ua=_.u.indexOf?function(a,b,c){return _.u.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.va=_.u.lastIndexOf?function(a,b,c){return _.u.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.v=_.u.forEach?function(a,b,c){_.u.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.wa=_.u.filter?function(a,b,c){return _.u.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.t(a)?a.split(""):a,l=0;l<d;l++)if(l in g){var r=g[l];b.call(c,r,l,a)&&(e[f++]=r)}return e};_.xa=_.u.map?function(a,b,c){return _.u.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.ya=_.u.reduce?function(a,b,c,d){d&&(b=(0,_.q)(b,d));return _.u.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.v)(a,function(c,g){e=b.call(d,e,c,g,a)});return e};_.za=_.u.some?function(a,b,c){return _.u.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Aa=function(a,b){var c=(0,_.ua)(a,b),d;(d=0<=c)&&_.u.splice.call(a,c,1);return d};
_.Ba=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var Da,Fa;_.Ca=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Da=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Ea=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};Fa=function(a){var b=arguments.length;if(1==b&&_.ma(arguments[0]))return Fa.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var Ha;_.w=function(){};_.x=function(a,b,c,d){a.a=null;b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.c=0===c?-1:0;a.F=b;a:{if(a.F.length&&(b=a.F.length-1,(c=a.F[b])&&"object"==typeof c&&!_.ma(c))){a.j=b-a.c;a.b=c;break a}a.j=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.c,a.F[c]=a.F[c]||_.Ga):a.b[c]=a.b[c]||_.Ga};_.Ga=[];_.y=function(a,b){if(b<a.j){var c=b+a.c,d=a.F[c];return d===_.Ga?a.F[c]=[]:d}d=a.b[b];return d===_.Ga?a.b[b]=[]:d};_.w.prototype.toString=function(){return this.F.toString()}; _.z=function(a,b){Ha[a]=b;b.messageId=a};Ha={};
Fa("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));_.Ia="StopIteration"in _.k?_.k.StopIteration:Error("f");_.Ja=function(){};_.Ja.prototype.next=function(){throw _.Ia;};_.Ja.prototype.ha=function(){return this};a:{var La=_.k.navigator;if(La){var Ma=La.userAgent;if(Ma){_.Ka=Ma;break a}}_.Ka=""}var A=function(a){return-1!=_.Ka.indexOf(a)};var Na=function(){return A("Opera")||A("OPR")},Oa=function(){return A("Edge")||A("Trident")||A("MSIE")},Pa=function(){return(A("Chrome")||A("CriOS"))&&!Na()&&!Oa()};var Qa=function(){return A("Edge")};var Ra=function(){return A("iPhone")&&!A("iPod")&&!A("iPad")};_.B=function(a,b){this.b={};this.a=[];this.j=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.B?(c=a.M(),d=a.B()):(c=_.Ea(a),d=Da(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.B.prototype.V=function(){return this.c};_.B.prototype.B=function(){Sa(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.B.prototype.M=function(){Sa(this);return this.a.concat()};
_.Ua=function(a,b){return Ta(a.b,b)};_.B.prototype.P=function(){return 0==this.c};_.B.prototype.clear=function(){this.b={};this.j=this.c=this.a.length=0};_.B.prototype.remove=function(a){return Ta(this.b,a)?(delete this.b[a],this.c--,this.j++,this.a.length>2*this.c&&Sa(this),!0):!1};
var Sa=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Ta(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Ta(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.B.prototype;_.h.get=function(a,b){return Ta(this.b,a)?this.b[a]:b};_.h.set=function(a,b){Ta(this.b,a)||(this.c++,this.a.push(a),this.j++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};
_.h.clone=function(){return new _.B(this)};_.h.ha=function(a){Sa(this);var b=0,c=this.a,d=this.b,e=this.j,f=this,g=new _.Ja;g.next=function(){for(;;){if(e!=f.j)throw Error("i");if(b>=c.length)throw _.Ia;var g=c[b++];return a?g:d[g]}};return g};var Ta=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Va=function(a){if("function"==typeof a.B)return a.B();if(_.t(a))return a.split("");if(_.la(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Da(a)};
_.Wa=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.la(a)||_.t(a))(0,_.v)(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.B)if(_.la(a)||_.t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=_.Ea(a);else d=void 0;for(var e=_.Va(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};
var Xa,Za,$a,bb,cb,db,fb,hb,ib,jb;Xa=Na();_.D=Oa();_.Ya=A("Gecko")&&!(-1!=_.Ka.toLowerCase().indexOf("webkit")&&!Qa())&&!(A("Trident")||A("MSIE"))&&!Qa();Za=-1!=_.Ka.toLowerCase().indexOf("webkit")&&!Qa();$a=_.k.navigator||null;_.ab=$a&&$a.platform||"";bb=function(){var a=_.Ka;if(_.Ya)return/rv\:([^\);]+)(\)|;)/.exec(a);if(_.D&&Qa())return/Edge\/([\d\.]+)/.exec(a);if(_.D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Za)return/WebKit\/(\S+)/.exec(a)};
cb=function(){var a=_.k.document;return a?a.documentMode:void 0};db=function(){if(Xa&&_.k.opera){var a=_.k.opera.version;return _.ja(a)?a():a}var a="",b=bb();b&&(a=b?b[1]:"");return _.D&&!Qa()&&(b=cb(),b>(0,window.parseFloat)(a))?String(b):a}();fb={};_.gb=function(a){return fb[a]||(fb[a]=0<=ta(db,a))};hb=_.k.document;ib=cb();jb=!hb||!_.D||!ib&&Qa()?void 0:ib||("CSS1Compat"==hb.compatMode?(0,window.parseInt)(db,10):5);
_.E=function(){this.C=this.C;this.j=this.j};_.E.prototype.C=!1;_.E.prototype.xb=function(){return this.C};_.E.prototype.D=function(){this.C||(this.C=!0,this.n())};_.G=function(a,b){_.kb(a,_.ha(_.F,b))};_.kb=function(a,b){a.C?b.call(void 0):(a.j||(a.j=[]),a.j.push(_.n(void 0)?(0,_.q)(b,void 0):b))};_.E.prototype.n=function(){if(this.j)for(;this.j.length;)this.j.shift()()};_.F=function(a){a&&"function"==typeof a.D&&a.D()};
_.lb=!_.D||_.D&&(Qa()||9<=jb);!_.Ya&&!_.D||_.D&&_.D&&(Qa()||9<=jb)||_.Ya&&_.gb("1.9.1");_.D&&_.gb("9");var mb=function(a){mb[" "](a);return a};mb[" "]=_.oa;_.nb=function(a,b){try{return mb(a[b]),!0}catch(c){}return!1};var ob,pb;ob=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.rb=function(a){if(pb){pb=!1;var b=_.k.location;if(b){var c=b.href;if(c&&(c=_.qb(c))&&c!=b.hostname)throw pb=!0,Error();}}return a.match(ob)};pb=Za;_.qb=function(a){return(a=_.rb(a)[3]||null)?(0,window.decodeURI)(a):a};
var sb=!_.D||_.D&&(Qa()||9<=jb),tb=_.D&&!_.gb("9");!Za||_.gb("528");_.Ya&&_.gb("1.9b")||_.D&&_.gb("8")||Xa&&_.gb("9.5")||Za&&_.gb("528");_.Ya&&!_.gb("8")||_.D&&_.gb("9");_.H=function(a,b){this.type=a;this.a=this.target=b;this.mc=!0};_.H.prototype.b=function(){this.mc=!1};var ub=function(a,b){_.H.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&_.Ya&&_.nb(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};_.p(ub,_.H); ub.prototype.b=function(){ub.t.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,tb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var vb,xb;vb="closure_listenable_"+(1E6*Math.random()|0);_.wb=function(a){return!(!a||!a[vb])};xb=0;var yb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ta=!!d;this.$a=e;this.key=++xb;this.removed=this.Sa=!1},zb=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.$a=null};var Ab=function(a){this.src=a;this.a={};this.b=0};Ab.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Bb(a,b,d,e);-1<g?(b=a[g],c||(b.Sa=!1)):(b=new yb(b,this.src,f,!!d,e),b.Sa=c,a.push(b));return b};Ab.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Bb(e,b,c,d);return-1<b?(zb(e[b]),_.u.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Cb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.Aa(a.a[c],b);d&&(zb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};Ab.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,zb(d[e]);delete this.a[c];this.b--}return b}; var Db=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Bb(a,c,d,e));return-1<b?a[b]:null},Bb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ta==!!c&&f.$a==d)return e}return-1};
var Eb,Fb,Gb,Lb,Nb,Sb,Rb,Ob,Kb,Tb;Eb="closure_lm_"+(1E6*Math.random()|0);Fb={};Gb=0;_.Hb=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)_.Hb(a,b[f],c,d,e);return null}c=_.Ib(c);return _.wb(a)?a.listen(b,c,d,e):_.Jb(a,b,c,!1,d,e)};_.Jb=function(a,b,c,d,e,f){if(!b)throw Error("l");var g=!!e,l=Kb(a);l||(a[Eb]=l=new Ab(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=Lb();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Nb(b.toString()),d);Gb++;return c};
Lb=function(){var a=Ob,b=sb?function(c){return a.call(b.src,b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b};_.Pb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)_.Pb(a,b[f],c,d,e);else c=_.Ib(c),_.wb(a)?a.Eb(b,c,d,e):a&&(a=Kb(a))&&(b=Db(a,b,c,!!d,e))&&_.Qb(b)};
_.Qb=function(a){if(_.ka(a)||!a||a.removed)return!1;var b=a.src;if(_.wb(b))return Cb(b.U,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ta):b.detachEvent&&b.detachEvent(Nb(c),d);Gb--;(c=Kb(b))?(Cb(c,a),0==c.b&&(c.src=null,b[Eb]=null)):zb(a);return!0};Nb=function(a){return a in Fb?Fb[a]:Fb[a]="on"+a};Sb=function(a,b,c,d){var e=!0;if(a=Kb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ta==c&&!f.removed&&(f=Rb(f,d),e=e&&!1!==f)}return e};
Rb=function(a,b){var c=a.qa,d=a.$a||a.src;a.Sa&&_.Qb(a);return c.call(d,b)};
Ob=function(a,b){if(a.removed)return!0;if(!sb){var c;if(!(c=b))a:{c=["window","event"];for(var d=_.k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new ub(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--){c.a=e[l];var r=Sb(e[l],f,!0,c),d=d&&r}for(l=0;l<e.length;l++)c.a=e[l],r=Sb(e[l],
f,!1,c),d=d&&r}return d}return Rb(a,new ub(b,this))};Kb=function(a){a=a[Eb];return a instanceof Ab?a:null};Tb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Ib=function(a){if(_.ja(a))return a;a[Tb]||(a[Tb]=function(b){return a.handleEvent(b)});return a[Tb]};
_.Ub=function(a){_.x(this,a,"h_cc",null)};_.p(_.Ub,_.w);_.z("h_cc",_.Ub);_.Ub.prototype.Z=function(){return _.y(this,19)};_.I=function(a){_.E.call(this);this.I=a;this.g={}};_.p(_.I,_.E);var Vb=[];_.I.prototype.listen=function(a,b,c,d){return _.Wb(this,a,b,c,d)};_.Wb=function(a,b,c,d,e,f){_.ma(c)||(c&&(Vb[0]=c.toString()),c=Vb);for(var g=0;g<c.length;g++){var l=_.Hb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!l)break;a.g[l.key]=l}return a};
_.I.prototype.Eb=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)this.Eb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.Ib(c),d=!!d,b=_.wb(a)?Db(a.U,String(b),c,d,e):a?(a=Kb(a))?Db(a,b,c,d,e):null:null,b&&(_.Qb(b),delete this.g[b.key]);return this};_.I.prototype.removeAll=function(){_.Ca(this.g,_.Qb);this.g={}};_.I.prototype.n=function(){_.I.t.n.call(this);this.removeAll()};_.I.prototype.handleEvent=function(){throw Error("m");};
var Xb=function(a,b,c){this.j=c;this.c=a;this.e=b;this.b=0;this.a=null};Xb.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var Yb=function(a,b){a.e(b);a.b<a.j&&(a.b++,b.next=a.a,a.a=b)};var Zb,$b,ac;Zb=function(a){_.k.setTimeout(function(){throw a;},0)};_.bc=function(a,b){var c=a;b&&(c=(0,_.q)(a,b));!_.ja(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype&&_.k.Window.prototype.setImmediate==_.k.setImmediate?($b||($b=ac()),$b(c)):_.k.setImmediate(c)};
ac=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!A("Presto")&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.q)(function(a){if(("*"==d||
a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Oa()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Qb;c.Qb=null;a()}};return function(a){d.next={Qb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")?function(a){var b=window.document.createElement("script"); b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};
var cc=function(){this.b=this.a=null},ec=new Xb(function(){return new dc},function(a){a.reset()},100);cc.prototype.add=function(a,b){var c=ec.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};cc.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var dc=function(){this.next=this.b=this.a=null};dc.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};dc.prototype.reset=function(){this.next=this.b=this.a=null};
var jc=function(a,b){fc||gc();hc||(fc(),hc=!0);ic.add(a,b)},fc,gc=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve();fc=function(){a.then(kc)}}else fc=function(){_.bc(kc)}},hc=!1,ic=new cc,kc=function(){for(var a=null;a=ic.remove();){try{a.a.call(a.b)}catch(b){Zb(b)}Yb(ec,a)}hc=!1};
_.J=function(){_.E.call(this);this.U=new Ab(this);this.L=this;this.u=null};_.p(_.J,_.E);_.J.prototype[vb]=!0;_.h=_.J.prototype;_.h.addEventListener=function(a,b,c,d){_.Hb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.Pb(this,a,b,c,d)};_.h.n=function(){_.J.t.n.call(this);this.U&&this.U.removeAll(void 0);this.u=null};_.h.listen=function(a,b,c,d){return this.U.add(String(a),b,!1,c,d)};_.h.Eb=function(a,b,c,d){return this.U.remove(String(a),b,c,d)}; _.h.da=function(a,b,c){a=this.U.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ta==b){var g=f.qa,l=f.$a||f.src;f.Sa&&Cb(this.U,f);d=!1!==g.call(l,c)&&d}}return d&&0!=c.mc};
var lc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},mc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var pc=function(a,b){this.a=0;this.g=void 0;this.j=this.b=this.c=null;this.e=this.f=!1;if(a==nc)oc(this,2,b);else try{var c=this;a.call(b,function(a){oc(c,2,a)},function(a){oc(c,3,a)})}catch(d){oc(this,3,d)}},qc=function(){this.next=this.b=this.j=this.c=this.a=null},rc,sc,nc;qc.prototype.reset=function(){this.b=this.j=this.c=this.a=null};rc=new Xb(function(){return new qc},function(a){a.reset()},100);sc=function(){var a=rc.get();a.c=null;a.j=null;a.b=null;return a};nc=function(){};
_.uc=function(){var a,b=new pc(function(b){a=b});return new tc(b,a)};pc.prototype.then=function(a,b,c){return vc(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};lc(pc);
var yc=function(a){0==a.a&&jc(function(){var a=new wc(void 0);xc(this,a)},a)},xc=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,g=c.b;g;g=g.next){var l=g.a;if(l&&(d++,l==a&&(e=g),e&&1<d))break;e||(f=g)}e&&(0==c.a&&1==d?xc(c,b):(f?(d=f,d.next==c.j&&(c.j=d),d.next=d.next.next):zc(c),Ac(c,e,3,b)))}a.c=null}else oc(a,3,b)},Cc=function(a,b){a.b||2!=a.a&&3!=a.a||Bc(a);a.j?a.j.next=b:a.b=b;a.j=b},vc=function(a,b,c,d){var e=sc();e.a=new pc(function(a,g){e.c=b?function(c){try{var e=
b.call(d,c);a(e)}catch(C){g(C)}}:a;e.j=c?function(b){try{var e=c.call(d,b);!_.n(e)&&b instanceof wc?g(b):a(e)}catch(C){g(C)}}:g});e.a.c=a;Cc(a,e);return e.a};pc.prototype.h=function(a){this.a=0;oc(this,2,a)};pc.prototype.k=function(a){this.a=0;oc(this,3,a)};
var oc=function(a,b,c){if(0==a.a){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(mc(c)){a.a=1;c.then(a.h,a.k,a);return}if(_.ia(c))try{var d=c.then;if(_.ja(d)){Dc(a,c,d);return}}catch(e){b=3,c=e}}a.g=c;a.a=b;a.c=null;Bc(a);3!=b||c instanceof wc||Ec(a,c)}},Dc=function(a,b,c){a.a=1;var d=!1,e=function(b){d||(d=!0,a.h(b))},f=function(b){d||(d=!0,a.k(b))};try{c.call(b,e,f)}catch(g){f(g)}},Bc=function(a){a.f||(a.f=!0,jc(a.l,a))},zc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,
b.next=null);a.b||(a.j=null);return b};pc.prototype.l=function(){for(var a=null;a=zc(this);)Ac(this,a,this.a,this.g);this.f=!1};var Ac=function(a,b,c,d){b.a&&(b.a.c=null);if(2==c)b.c.call(b.b,d);else{if(b.a)for(;a&&a.e;a=a.c)a.e=!1;b.j.call(b.b,d)}Yb(rc,b)},Ec=function(a,b){a.e=!0;jc(function(){a.e&&Fc.call(null,b)})},Fc=Zb,wc=function(a){_.qa.call(this,a)};_.p(wc,_.qa);wc.prototype.name="cancel";var tc=function(a,b){this.b=a;this.a=b};
var Hc,Ic,Jc,Kc,Lc;_.Gc=A("Firefox");Hc=Ra()||A("iPod");Ic=A("iPad");Jc=A("Android")&&!(Pa()||A("Firefox")||Na()||A("Silk"));Kc=Pa();Lc=A("Safari")&&!(Pa()||A("Coast")||Na()||Oa()||A("Silk")||A("Android"))&&!(Ra()||A("iPad")||A("iPod"));_.Mc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Nc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.Oc=function(a,b){this.j=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.e=null;this.h=b||"u";this.a=this.g=null;this.f=[]};_.Oc.prototype.message=function(){var a={};a.i=this.a;a.m=this.f;a.r=this.h;a.o=this.g;a.s=this.b;a.st=this.c;a.d=this.e;a.dt=this.j;return a};_.ga("ace.base.Message.prototype.message",_.Oc.prototype.message);
_.Pc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.a=b[c];break;case "m":a.f=b[c];break;case "o":a.g=b[c];break;case "s":a.b=b[c];break;case "d":a.e=b[c];break;case "st":a.c=b[c];break;case "dt":a.j=b[c]}return a};_.Qc=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))};_.Rc=function(a,b){null!=b&&(a.a=b)};_.Sc=function(a,b){"object"==typeof b?a.f=b:a.f=[b]};_.Oc.prototype.source=function(){return this.b};_.Oc.prototype.target=function(){return this.e}; _.Oc.prototype.content=function(){return this.f};
_.Tc=function(a,b,c,d,e){_.E.call(this);this.b=a;this.Pa=b;this.a=typeof b;this.zb=c?c:!1;this.ba=!0;this.vb=d?d:!1;this.pb=e?e:!1};_.p(_.Tc,_.E);_.h=_.Tc.prototype;_.h.n=function(){_.Tc.t.n.call(this);this.b="";this.Pa=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.G=function(){return this.Pa};_.h.setEnabled=function(a){this.ba=a};
var Uc=function(a){return(a=a.exec(_.Ka))?a[1]:""},Vc=function(){if(_.Gc)return Uc(/Firefox\/([0-9.]+)/);if(_.D||Xa)return db;if(Kc)return Uc(/Chrome\/([0-9.]+)/);if(Lc&&!(Ra()||A("iPad")||A("iPod")))return Uc(/Version\/([0-9.]+)/);if(Hc||Ic){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Ka))return a[1]+"."+a[2]}else if(Jc)return(a=Uc(/Android\s+([0-9.]+)/))?a:Uc(/Version\/([0-9.]+)/);return""}();
_.Xc=function(a){_.E.call(this);this.a=new _.B;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&_.Wc(this,a)};_.p(_.Xc,_.E);_.Yc=0<=ta(Vc,"23.0.1262.0")&&!_.Nc();_.Xc.prototype.n=function(){_.Xc.t.n.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.F(this.a.get(a[b]));delete this.a};_.Xc.prototype.getItem=function(a){return _.Ua(this.a,a)?this.a.get(a):null};
_.Xc.prototype.setItem=function(a){this.a.set(a.id(),a)};_.Wc=function(a,b){for(var c in b){var d=b[c],e=null;_.Ua(a.a,c)?(e=a.a.get(c),e.Pa=d.value,d.changed&&(e.pb=d.changed)):(e=new _.Tc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.ad=function(){this.c=new _.B;this.a=null;this.b=!1;this.a=new Zc;this.b=!0;_.$c(this)};_.ad.ua=function(){return _.ad.a?_.ad.a:_.ad.a=new _.ad};_.$c=function(a,b){var c=b||_.oa;a.b?c():window.chrome.storage.local.get((0,_.q)(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};_.ad.prototype.get=function(a){return this.a.get(a)};_.ad.prototype.set=function(a,b){var c=_.uc();this.a.set(a,b);c.a(void 0);return c.b};_.ad.prototype.remove=function(a){this.a.remove(a)};
_.ad.prototype.clear=function(){this.a.clear()};var Zc=function(){this.a=window.localStorage};Zc.prototype.clear=function(){this.a.clear()};Zc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ha[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};Zc.prototype.set=function(a,b){var c=null;b instanceof _.w&&(b=b.F,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}}; Zc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
_.bd=function(a,b){this.b=a;this.a=b;this.constructor.Ob||(this.constructor.Ob={});this.constructor.Ob[this.toString()]=this};_.bd.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};_.K=function(a,b){_.bd.call(this,a,b)};_.p(_.K,_.bd);_.cd=function(a){this.a=a};_.dd=new _.cd("lib");_.L=function(a){this.a=a};_.L.prototype.toString=function(){return this.a};_.ed=new _.L("fJuxOc");_.fd=new _.L("ZtVrH");_.gd=new _.L("zZa4xc");_.hd=new _.L("pVbxBc");_.id=new _.L("byfTOb");_.jd=new _.L("LEikZe");_.kd=new _.L("rJmJrc");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.ld=function(a,b){this.j=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.f=!1;this.e=0;this.h=null;this.q=0};_.ld.prototype.k=function(a,b){this.f=!1;_.md(this,a,b)};_.md=function(a,b,c){a.a=!0;a.c=c;a.b=!b;nd(a)};_.pd=function(a){if(a.a){if(!a.l)throw new od;a.l=!1}};_.ld.prototype.g=function(a){_.pd(this);_.md(this,!0,a)};_.qd=function(a,b,c,d){a.j.push([b,c,d]);a.a&&nd(a)};
_.ld.prototype.then=function(a,b,c){var d,e,f=new pc(function(a,b){d=a;e=b});_.qd(this,d,function(a){"undefined"!=typeof _.rd&&a instanceof _.rd?yc(f):e(a)});return f.then(a,b,c)};lc(_.ld);
var sd=function(a){return(0,_.za)(a.j,function(a){return _.ja(a[1])})},nd=function(a){if(a.e&&a.a&&sd(a)){var b=a.e,c=td[b];c&&(_.k.clearTimeout(c.Wa),delete td[b]);a.e=0}a.h&&(a.h.q--,delete a.h);for(var b=a.c,d=c=!1;a.j.length&&!a.f;){var e=a.j.shift(),f=e[0],g=e[1],e=e[2];if(f=a.b?g:f)try{var l=f.call(e||a.u,b);_.n(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);mc(b)&&(d=!0,a.f=!0)}catch(r){b=r,a.b=!0,sd(a)||(c=!0)}}a.c=b;d&&(l=(0,_.q)(a.k,a,!0),d=(0,_.q)(a.k,a,!1),b instanceof _.ld?(_.qd(b,
l,d),b.p=!0):b.then(l,d));c&&(b=new ud(b),td[b.Wa]=b,a.e=b.Wa)},od=function(){_.qa.call(this)};_.p(od,_.qa);od.prototype.message="Deferred has already fired";od.prototype.name="AlreadyCalledError";var ud=function(a){this.Wa=_.k.setTimeout((0,_.q)(this.b,this),0);this.a=a};ud.prototype.b=function(){delete td[this.Wa];throw this.a;};var td={};

}catch(e){_._DumpException(e)}
try{
var Ed,Fd,Gd,Id,Jd,Kd,Ld,Rd,Sd,Td,Xd,Yd,ae,be,ce,de,ee,fe,ge,le;Ed={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};Fd=function(a,b){b.push('"',a.replace(_.Ba,function(a){if(a in Ed)return Ed[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Ed[a]=e+b.toString(16)}),'"')};
Gd=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)Gd(a,b[f],c,d,e);return null}c=_.Ib(c);return _.wb(a)?a.U.add(String(b),c,!0,d,e):_.Jb(a,b,c,!0,d,e)};Id="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
Jd=function(a,b,c){switch(typeof b){case "string":Fd(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(_.ma(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),Jd(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),Fd(e,c),c.push(":"),
Jd(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("d`"+typeof b);}};Kd=function(){};Ld=function(a,b,c,d,e,f){if(_.ma(c))for(var g=0;g<c.length;g++)Ld(a,b,c[g],d,e,f);else{b=Gd(b,c,d||a.handleEvent,e,f||a.I||a);if(!b)return a;a.g[b.key]=b}return a};_.M=function(a,b,c){b<a.j?a.F[b+a.c]=c:a.b[b]=c};
_.Md=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Id.length;f++)c=Id[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.Nd=function(a){var b=[];Jd(new Kd,a,b);return b.join("")};_.Od=function(a,b,c){null!=b&&(a.e=b,null!=c&&(a.j=c))};
_.O=function(a,b){var c,d=a.u;if(d)for(c=[];d;d=d.u)c.push(d);var d=a.L,e=b,f=e.type||e;if(_.t(e))e=new _.H(e,d);else if(e instanceof _.H)e.target=e.target||d;else{var g=e,e=new _.H(f,d);_.Md(e,g)}var g=!0,l;if(c)for(var r=c.length-1;0<=r;r--)l=e.a=c[r],g=l.da(f,!0,e)&&g;l=e.a=d;g=l.da(f,!0,e)&&g;g=l.da(f,!1,e)&&g;if(c)for(r=0;r<c.length;r++)l=e.a=c[r],g=l.da(f,!1,e)&&g};_.Pd=function(a,b,c,d){return Ld(a,b,c,d,void 0)};_.Qd=function(a,b,c){a.a||(a.a={});var d=c?c.F:c;a.a[b]=c;_.M(a,b,d)};
_.P=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=_.y(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};Rd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Sd=function(a,b){return a?b?(0,window.decodeURI)(a):(0,window.decodeURIComponent)(a):""};Td=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};
_.Ud=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.Vd=function(a){return _.u.concat.apply(_.u,arguments)};_.Wd=function(a,b,c){this.a=a||null;this.b=!!c};Xd=function(a){a.H||(a.H=new _.B,a.O=0,a.a&&Td(a.a,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};_.h=_.Wd.prototype;_.h.H=null;_.h.O=null;_.h.V=function(){Xd(this);return this.O};
_.h.add=function(a,b){Xd(this);this.a=null;a=Yd(this,a);var c=this.H.get(a);c||this.H.set(a,c=[]);c.push(b);this.O++;return this};_.h.remove=function(a){Xd(this);a=Yd(this,a);return _.Ua(this.H,a)?(this.a=null,this.O-=this.H.get(a).length,this.H.remove(a)):!1};_.h.clear=function(){this.H=this.a=null;this.O=0};_.h.P=function(){Xd(this);return 0==this.O};var Zd=function(a,b){Xd(a);b=Yd(a,b);return _.Ua(a.H,b)};
_.Wd.prototype.M=function(){Xd(this);for(var a=this.H.B(),b=this.H.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.Wd.prototype.B=function(a){Xd(this);var b=[];if(_.t(a))Zd(this,a)&&(b=_.Vd(b,this.H.get(Yd(this,a))));else{a=this.H.B();for(var c=0;c<a.length;c++)b=_.Vd(b,a[c])}return b};_.Wd.prototype.set=function(a,b){Xd(this);this.a=null;a=Yd(this,a);Zd(this,a)&&(this.O-=this.H.get(a).length);this.H.set(a,[b]);this.O++;return this};
_.Wd.prototype.get=function(a,b){var c=a?this.B(a):[];return 0<c.length?String(c[0]):b};_.$d=function(a,b,c){a.remove(b);0<c.length&&(a.a=null,a.H.set(Yd(a,b),_.Ud(c)),a.O+=c.length)};_.Wd.prototype.toString=function(){if(this.a)return this.a;if(!this.H)return"";for(var a=[],b=this.H.M(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.B(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}return this.a=a.join("&")};
_.Wd.prototype.clone=function(){var a=new _.Wd;a.a=this.a;this.H&&(a.H=this.H.clone(),a.O=this.O);return a};Yd=function(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c};ae=function(a,b){b&&!a.b&&(Xd(a),a.a=null,a.H.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.$d(this,e,a))},a));a.b=b};be=/#/g;ce=/[\#\?@]/g;de=/[\#\?]/g;ee=/[\#\?:]/g;fe=/[#\/\?@]/g;
ge=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,Rd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};_.he=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36)};
_.ie=function(a,b){var c;"undefined"!=typeof _.ie&&a instanceof _.ie?(this.ma=_.n(b)?b:a.ma,_.je(this,a.fa),this.sa=a.sa,this.R=a.R,_.ke(this,a.ea),this.N=a.N,le(this,a.a.clone()),this.la=a.la):a&&(c=_.rb(String(a)))?(this.ma=!!b,_.je(this,c[1]||"",!0),this.sa=Sd(c[2]||""),this.R=Sd(c[3]||"",!0),_.ke(this,c[4]),this.N=Sd(c[5]||"",!0),le(this,c[6]||"",!0),this.la=Sd(c[7]||"")):(this.ma=!!b,this.a=new _.Wd(null,0,this.ma))};_.h=_.ie.prototype;_.h.fa="";_.h.sa="";_.h.R="";_.h.ea=null;_.h.N="";
_.h.la="";_.h.ma=!1;_.h.toString=function(){var a=[],b=this.fa;b&&a.push(ge(b,fe,!0),":");if(b=this.R){a.push("//");var c=this.sa;c&&a.push(ge(c,fe,!0),"@");a.push((0,window.encodeURIComponent)(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.ea;null!=b&&a.push(":",String(b))}if(b=this.N)this.R&&"/"!=b.charAt(0)&&a.push("/"),a.push(ge(b,"/"==b.charAt(0)?de:ee,!0));(b=this.a.toString())&&a.push("?",b);(b=this.la)&&a.push("#",ge(b,be));return a.join("")};
_.me=function(a,b){var c=a.clone(),d=!!b.fa;d?_.je(c,b.fa):d=!!b.sa;d?c.sa=b.sa:d=!!b.R;d?c.R=b.R:d=null!=b.ea;var e=b.N;if(d)_.ke(c,b.ea);else if(d=!!b.N){if("/"!=e.charAt(0))if(a.R&&!a.N)e="/"+e;else{var f=c.N.lastIndexOf("/");-1!=f&&(e=c.N.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),g=[],l=0;l<f.length;){var r=f[l++];"."==r?e&&l==f.length&&g.push(""):".."==r?((1<g.length||1==g.length&&""!=g[0])&&
g.pop(),e&&l==f.length&&g.push("")):(g.push(r),e=!0)}e=g.join("/")}else e=f}d?c.N=e:d=""!==b.a.toString();d?le(c,Sd(b.a.toString())):d=!!b.la;d&&(c.la=b.la);return c};_.ie.prototype.clone=function(){return new _.ie(this)};_.je=function(a,b,c){a.fa=c?Sd(b,!0):b;a.fa&&(a.fa=a.fa.replace(/:$/,""))};_.ke=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("j`"+b);a.ea=b}else a.ea=null};le=function(a,b,c){b instanceof _.Wd?(a.a=b,ae(a.a,a.ma)):(c||(b=ge(b,ce)),a.a=new _.Wd(b,0,a.ma))};
_.R=function(a,b,c){a.a.set(b,c)};_.ne=function(a,b,c){_.ma(c)||(c=[String(c)]);_.$d(a.a,b,c)};_.oe=function(a,b){return a.a.get(b)};_.pe=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.qe=function(a,b){return 0<=(0,_.ua)(a,b)};
_.re=function(a,b,c){if(_.ja(a))c&&(a=(0,_.q)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.q)(a.handleEvent,a);else throw Error("n");return 2147483647<b?-1:_.k.setTimeout(a,b||0)};_.se=function(a){_.k.clearTimeout(a)};_.te=function(a){var b={},c;for(c in a)b[c]=a[c];return b};_.ue=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.la(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}}; _.ve=function(a,b){var c;a:{c=a.length;for(var d=_.t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:_.t(a)?a.charAt(c):a[c]};
var ze,xe,ye,Ae;_.we=function(){};ze=function(a){var b=a.ia,c=function(a){c.t.constructor.call(this,a);var b=this.T.length;this.a=[];for(var d=0;d<b;++d)this.T[d].yd||(this.a[d]=new this.T[d](a))};_.p(c,b);for(var d=[];a;){if(b=a.ia){b.T&&_.ue(d,b.T);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ja(e[f])&&e[f]!==b){var g=!!e[f].Jc,l=xe(f,e,d,g);(g=ye(f,e,l,g))&&(c.prototype[f]=g)}}a=a.t&&a.t.constructor}c.prototype.T=d;return c};
xe=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e};
ye=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.T[c[0]].prototype[a].apply(this,arguments)}:b[a].Lc?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var r=this.a[c[e]];if(r=r?r[a].apply(r,d):this.T[c[e]].prototype[a].apply(this,d)){d=r;break a}}d=!1}return d}:b[a].Kc?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var r=this.a[c[e]],r=r?r[a].apply(r,
d):this.T[c[e]].prototype[a].apply(this,d);if(null!=r){d=r;break a}}d=void 0}return d}:b[a].gc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var r=this.a[c[e]];r?r[a].apply(r,d):this.T[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],r=0;r<c.length;++r){var C=this.a[c[r]];e.push(C?C[a].apply(C,d):this.T[c[r]].prototype[a].apply(this,d))}return e}:d||b[a].Lc||b[a].Kc||b[a].gc?e=null:e=Ae;return e};Ae=function(){return[]}; _.we.prototype.tb=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var Be;_.Ce=function(a){if(!a.qb){var b;for(b=a.constructor;b&&!b.ia;)b=b.t&&b.t.constructor;b.ia.Tb||(b.ia.Tb=ze(b));b=new b.ia.Tb(a);a.qb=b;a.tb||(a.tb=Be)}};Be=function(a){return this.qb.tb(a)};var De=function(){};De.prototype.a=null;var Fe=function(a){var b;(b=a.a)||(b={},Ee(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var Ge,He=function(){};_.p(He,De);var Ie=function(a){return(a=Ee(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},Ee=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("t");}return a.b};Ge=new He;
var Ke,Ne,Se,Ue,Te,Pe;_.Je=function(a){_.J.call(this);this.A=new _.B;this.k=a||null;this.b=!1;this.h=this.a=null;this.q="";this.e=0;this.c=this.p=this.f=this.l=!1;this.v=0;this.g=null;this.I="";this.w=this.aa=!1};_.p(_.Je,_.J);Ke=/^https?$/i;_.Le=["POST","PUT"];_.Me=[];_.Je.prototype.S=function(){this.D();_.Aa(_.Me,this)};
_.Je.prototype.send=function(a,b,c,d){if(this.a)throw Error("u`"+this.q+"`"+a);b=b?b.toUpperCase():"GET";this.q=a;this.e=0;this.l=!1;this.b=!0;this.a=this.k?Ie(this.k):Ie(Ge);this.h=this.k?Fe(this.k):Fe(Ge);this.a.onreadystatechange=(0,_.q)(this.J,this);try{this.p=!0,this.a.open(b,String(a),!0),this.p=!1}catch(e){Ne(this);return}a=c||"";var f=this.A.clone();d&&_.Wa(d,function(a,b){f.set(b,a)});d=_.ve(f.M(),Oe);c=_.k.FormData&&a instanceof _.k.FormData;!_.qe(_.Le,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.I&&(this.a.responseType=this.I);"withCredentials"in this.a&&(this.a.withCredentials=this.aa);try{Pe(this),0<this.v&&((this.w=Qe(this.a))?(this.a.timeout=this.v,this.a.ontimeout=(0,_.q)(this.K,this)):this.g=_.re(this.K,this.v,this)),this.f=!0,this.a.send(a),this.f=!1}catch(g){Ne(this)}};var Qe=function(a){return _.D&&_.gb(9)&&_.ka(a.timeout)&&_.n(a.ontimeout)},Oe=function(a){return"content-type"==a.toLowerCase()};
_.Je.prototype.K=function(){"undefined"!=typeof _.aa&&this.a&&(this.e=8,_.O(this,"timeout"),_.Re(this,8))};Ne=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.e=5;Se(a);Te(a)};Se=function(a){a.l||(a.l=!0,_.O(a,"complete"),_.O(a,"error"))};_.Re=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.e=b||7,_.O(a,"complete"),_.O(a,"abort"),Te(a))};_.Je.prototype.n=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Te(this,!0));_.Je.t.n.call(this)};
_.Je.prototype.J=function(){this.C||(this.p||this.f||this.c?Ue(this):this.W())};_.Je.prototype.W=function(){Ue(this)};Ue=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.h[1]||4!=(a.a?a.a.readyState:0)||2!=_.Ve(a)))if(a.f&&4==(a.a?a.a.readyState:0))_.re(a.J,0,a);else if(_.O(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.We(a)?(_.O(a,"complete"),_.O(a,"success")):(a.e=6,Se(a))}finally{Te(a)}}};
Te=function(a,b){if(a.a){Pe(a);var c=a.a,d=a.h[0]?_.oa:null;a.a=null;a.h=null;b||_.O(a,"ready");try{c.onreadystatechange=d}catch(e){}}};Pe=function(a){a.a&&a.w&&(a.a.ontimeout=null);_.ka(a.g)&&(_.se(a.g),a.g=null)};
_.We=function(a){var b=_.Ve(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=_.rb(String(a.q))[1]||null,!a&&window.self.location&&(a=window.self.location.protocol,a=a.substr(0,a.length-1)),b=!Ke.test(a?a.toLowerCase():"");c=b}return c};_.Ve=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};_.Xe=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
_.Ye=function(a){_.x(this,a,"h_icr",null)};_.p(_.Ye,_.w);_.z("h_icr",_.Ye);_.Ze=function(a){_.x(this,a,"h_cs",null)};_.p(_.Ze,_.w);_.z("h_cs",_.Ze);_.Ze.prototype.getState=function(){return _.y(this,1)};_.$e=new _.L("HwdKC");
}catch(e){_._DumpException(e)}
try{
_.k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_description:{message:"Always stay connected with the new desktop app for Hangouts on ChromeOS and Windows."},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},
chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},chrome_app_signin_button:{message:"Sign in"},chrome_app_outdated_title:{message:"Update your Hangouts Chrome app"},chrome_app_outdated_detail:{message:"This app is out of date. There's a newer version available."},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_title_2:{message:"Do you want to quit Hangouts?"},chrome_app_exit_detail:{message:"You will not receive new messages or calls on this device"},
chrome_app_exit_detail_2:{message:"You can also choose to minimize it and continue to receive messages and calls."},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"},chrome_app_exit_minimize:{message:"Minimize"},chrome_app_osx_warning_message:{message:"Hangouts Chrome app is not fully supported on Mac OSX."},chrome_app_osx_warning_ack:{message:"OK, GOT IT"}};

}catch(e){_._DumpException(e)}
try{
_.Xh=function(a){for(var b=a.a.M(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.G(),type:f.type(),multiple:f.zb,disabled:!f.ba,inverse:f.vb,changed:f.pb}}return c};_.Yh=function(a,b){return _.t(b)?a.getElementById(b):b};_.S=function(a){return _.Yh(window.document,a)};_.Zh=new _.L("a");_.$h=new _.L("b");_.ai=new _.L("c");_.bi=new _.L("d");_.ci=new _.L("e");_.di=new _.L("f");_.ei=new _.L("g");_.fi=new _.L("h");_.Bd=new _.L("i");_.gi=new _.L("j");
_.T=function(a){var b;b=b||[];b.length||(b[0]="");var c=window.chrome.i18n.getMessage(a,b);if(c)return c;(c=(c=_.k.ace_i18n[a.toLowerCase()])?c.message:_.k.ace_i18n["MSG_"+a])&&(c=c.replace("$1",b[0]).replace("$2",b[1]).replace("$3",b[2]));return c};
}catch(e){_._DumpException(e)}
try{
var hi,ii,ji,ki,li,ni,pi,qi,ri,si,ti,ui,vi,wi,xi,yi,zi,Bi,Ci,Di,Hi,Ji,Ni;hi=function(a){return a.b[0]};ii=function(a){return(a=a.a.get("TopMost"))&&a.ba?a.G():!0};ji=function(){return!0};ki={};li=0;_.mi=function(a){a&&a!=window.chrome.windows.WINDOW_ID_NONE&&window.chrome.windows.update(a,{focused:!0})};ni=function(a){if(ki[a])return ki[a];a=String(a);if(!ki[a]){var b=/function ([^\(]+)/.exec(a);ki[a]=b?b[1]:"[Anonymous]"}return ki[a]};_.oi=function(a){return a[_.ba]||(a[_.ba]=++li)};
pi=function(a){window.chrome.windows.getAll({populate:!0},function(b){for(var c=0;c<b.length;++c){var d=b[c].tabs;if(null!=d)for(var e=0;e<d.length;++e)if(d[e].selected&&d[e].url==a){_.mi(b[c].id);return}}})};qi=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};ri=function(){return null!=window.navigator.platform.match(/Mac.*/)};si=function(){return!_.Nc()&&null!=window.navigator.platform.match(/Linux.*/)};ti=function(a){this.a=a||_.k.document||window.document};
ti.prototype.Yb=function(){var a=this.a;return a.parentWindow||a.defaultView};ti.prototype.contains=_.pe;
ui=function(a,b){var c=[];if(_.qe(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(ni(a)+"(");for(var d=a.arguments,e=0;d&&e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=ni(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}b.push(a);c.push(")\n");try{c.push(ui(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")};vi=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+_.oi(a):b.substr(0,1)+a};wi=function(a){if(a instanceof _.Ja)return a;if("function"==typeof a.ha)return a.ha(!1);if(_.la(a)){var b=0,c=new _.Ja;c.next=function(){for(;;){if(b>=a.length)throw _.Ia;if(b in a)return a[b++];b++}};return c}throw Error("g");};xi=function(a,b){return a>b?1:a<b?-1:0};
yi=function(a,b){null!=a&&(window.open(a,"winid_"+(new Date).getTime(),b),_.re((0,_.q)(pi,null,a),1E3))};zi=function(a){null!=a&&(a=window.chrome.runtime.getURL("images_4/"+a));return a};_.Ai=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};_.Ai.prototype.clone=function(){return new _.Ai(this.left,this.top,this.width,this.height)};
_.Ai.prototype.contains=function(a){return"undefined"!=typeof _.Ai&&a instanceof _.Ai?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};_.Ai.prototype.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.Ai.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.U=function(a){return _.U.b(a)};_.U.b=function(a){return a+"_"};_.U.g=function(){throw Error("o");};_.U.e=function(a){if(a&&a.constructor&&a.constructor.toString()===Object.toString()){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[_.U.b(c)]=a[c]);return b}throw Error("p");};_.U.c=!0;_.U.j=function(a){return a};_.U.f=function(){return!0};
Bi=[/^https?:\/\/.*.google.com(:[0-9]+)?\/talkgadget\/success/,/^https:\/\/accounts.google.com\/ServiceLogin/];Ci=[1E4,12E4,144E5];Di=[200,2E3,3E5];_.Ei=function(a,b){_.J.call(this);this.c=a||1;this.b=b||_.k;this.f=(0,_.q)(this.h,this);this.g=(0,_.m)()};_.p(_.Ei,_.J);_.Ei.prototype.e=!1;_.Ei.prototype.a=null;_.Ei.prototype.setInterval=function(a){this.c=a;this.a&&this.e?(this.stop(),_.Fi(this)):this.a&&this.stop()};
_.Ei.prototype.h=function(){if(this.e){var a=(0,_.m)()-this.g;0<a&&a<.8*this.c?this.a=this.b.setTimeout(this.f,this.c-a):(this.a&&(this.b.clearTimeout(this.a),this.a=null),_.O(this,"tick"),this.e&&(this.a=this.b.setTimeout(this.f,this.c),this.g=(0,_.m)()))}};_.Fi=function(a){a.e=!0;a.a||(a.a=a.b.setTimeout(a.f,a.c),a.g=(0,_.m)())};_.Ei.prototype.stop=function(){this.e=!1;this.a&&(this.b.clearTimeout(this.a),this.a=null)};_.Ei.prototype.n=function(){_.Ei.t.n.call(this);this.stop();delete this.b};
var Gi=function(a,b){this.width=a;this.height=b};Gi.prototype.clone=function(){return new Gi(this.width,this.height)};Gi.prototype.P=function(){return!(this.width*this.height)};Gi.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};Gi.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};Hi=function(a){var b;b||(b=ui(a||arguments.callee.caller,[]));return b};
_.Ii=function(a){this.a=new _.B;if(a){a=_.Va(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])}};_.h=_.Ii.prototype;_.h.V=function(){return this.a.V()};_.h.add=function(a){this.a.set(vi(a),a)};_.h.removeAll=function(a){a=_.Va(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};_.h.remove=function(a){return this.a.remove(vi(a))};_.h.clear=function(){this.a.clear()};_.h.P=function(){return this.a.P()};_.h.contains=function(a){return _.Ua(this.a,vi(a))};_.h.B=function(){return this.a.B()};
_.h.clone=function(){return new _.Ii(this)};_.h.ha=function(){return this.a.ha(!1)};Ji=function(a,b){if(_.la(a))try{(0,_.v)(a,b,void 0)}catch(c){if(c!==_.Ia)throw c;}else{a=wi(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(d){if(d!==_.Ia)throw d;}}};_.Ki=function(a,b,c){a.a||(a.a={});c=c||[];for(var d=[],e=0;e<c.length;e++)d[e]=c[e].F;a.a[b]=c;_.M(a,b,d)};
_.Li=function(a,b,c){a.a||(a.a={});if(!a.a[c]){for(var d=_.y(a,c),e=[],f=0;f<d.length;f++)e[f]=new b(d[f]);a.a[c]=e}b=a.a[c];b==_.Ga&&(b=a.a[c]=[]);return b};_.Mi=function(a,b){a.sort(b||xi)};Ni=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};
var Oi=function(a){_.x(this,a,"dpgi",null)};_.p(Oi,_.w);_.z("dpgi",Oi);var Pi=function(a){_.x(this,a,"dri",null)};_.p(Pi,_.w);_.z("dri",Pi);_.Ri=function(a){_.x(this,a,"di",Qi)};_.p(_.Ri,_.w);var Qi=[6,7,10,11,12];_.z("di",_.Ri);_.Si=function(a){_.x(this,a,"e",null)};_.p(_.Si,_.w);_.z("e",_.Si);_.Ti=function(a){_.x(this,a,"f.ri",null)};_.p(_.Ti,_.w);_.z("f.ri",_.Ti);var Ui=function(){_.E.call(this)},Vi;_.p(Ui,_.E);
_.Xi=function(a,b){var c=Vi;if(!(c.C||"undefined"!=typeof _.rd&&b instanceof _.rd))if(c.b){var c=c.b,d=Wi();d["call-stack"]=Hi();a&&(d.message=a);var e;b instanceof Error?e=b:e=b||"";var f,g="";e&&(g=(e.lineNumber||"unknown")+":"+Ni(e.fileName||"unknown")+":"+Ni(e.message||"unknown"));var l="";for(f in d){var r;r="call-stack"==f?d[f].replace(/\(.*\)/g,""):d[f];l=l+f+":"+r+":"}f=g+"::"+l;g=c.c[f];g||(g={time:0,count:0},c.c[f]=g);if(1E4>(0,_.m)()-g.time)g.count++,1==g.count&&(d=Wi(),d.message="Throttling: "+ f,c.a.a(e,d));else{g.count&&(d["dropped-instances"]=g.count);g.time=(0,_.m)();for(f=g.count=0;f<c.b.length;f++)c.b[f](e,d);c.a.a(e,d)}}else c.a&&10>c.a.length&&c.a.push([a,b])};Vi=new Ui;
_.Yi=function(a){var b=window;if(!b.location){var c;try{c=_.Nd(b)}catch(d){c=_.Ea(b).toString()}_.Xi(null,Error("x`"+c))}c=b.location&&b.location.ancestorOrigins;if(_.n(c))return c&&c.length?c[a?0:c.length-1]==b.location.origin:!0;try{return _.n((a?b.parent:b.top).location.href)}catch(e){return!1}};
var Zi={},Wi=function(){var a={};a.location=window.document.location.toString();if(_.Yi(!1))try{a["top.location"]=window.top.location.toString()}catch(b){a["top.location"]="[external]"}else a["top.location"]="[external]";for(var c in Zi)try{a[c]=Zi[c].call()}catch(d){a[c]="[error] "+d.message}return a};
var W=new _.cd("act"),$i=new _.cd("impr"),aj=new _.cd("tran"),bj=new _.cd("perf");new _.K(W,1);new _.K(W,2);new _.K(W,3);new _.K(W,4);new _.K(W,5);new _.K(W,6);new _.K(W,7);new _.K(W,8);new _.K(W,9);new _.K(W,10);new _.K(W,11);new _.K(W,12);new _.K(W,25);new _.K(W,13);new _.K(W,14);new _.K(W,15);new _.K(W,22);new _.K(W,16);new _.K(W,17);new _.K(W,18);new _.K(W,19);new _.K(W,20);new _.K(W,21);new _.K(W,23);new _.K(W,24);new _.K(W,26);new _.K(W,27);_.cj=new _.K($i,1E3);new _.K(aj,1001);new _.K(bj,1002);
_.dj=new _.L("k");_.gj=function(a){this.l=a;this.q=a.get(_.ei);this.b=a.get(_.fi);this.a=1;this.e=this.k=null;this.g=this.c=!1;this.p=(0,_.q)(this.u,this);ej(this);fj(this);null!=this.b.a.get("UnreadIndicator")&&this.b.remove("UnreadIndicator");null!=this.b.a.get("app_status")&&this.b.remove("app_status");null!=this.b.a.get("user_id")&&this.b.remove("user_id");null!=this.b.a.get("client_state")&&this.b.remove("client_state")};_.p(_.gj,_.E);_.ga("ace.core.DesktopManager",_.gj);_.gj.prototype.n=function(){hj(this);_.gj.t.n.call(this)};
_.gj.prototype.f=function(a,b){this.a!=b&&(this.a=b,fj(this),ij(this),1==this.a&&(this.e=this.k=null,this.g=this.c=!1,hj(this),this.q.j(),this.l.get(_.ci).b()),_.V.g())};_.gj.prototype.changeDesktop=_.gj.prototype.f;_.gj.prototype.v=function(a,b){this.c!=b&&(this.c=b,fj(this),ij(this))};_.gj.prototype.setMainUiShowing=_.gj.prototype.v;_.gj.prototype.h=function(){return this.c};
var ej=function(a){var b=a.q.a,c;if(c=null!=window.navigator.platform.match(/Win.*/)||si()||ri())c=b.a.get("StopOnBrowserClose"),(c=c&&c.ba?c.G():!1)||(c=(b=b.a.get("TrayIcon"))&&b.ba?b.G():!1);c&&window.chrome.systemIndicator&&(window.chrome.systemIndicator.enable(),window.chrome.systemIndicator.onClicked.addListener(a.p))},hj=function(a){window.chrome.systemIndicator&&(window.chrome.systemIndicator.disable(),window.chrome.systemIndicator.onClicked.removeListener(a.p))},ij=function(a){var b;switch(a.a){case 2:b=
_.T("QUASAR_TIP_CONNECTING");break;case 3:b=_.T("QUASAR_TIP_NOT_LOGIN");break;case 4:case 9:case 8:b=a.c?a.g?_.T("CHROME_EXT_TIP_CONNECTED_MISSED_MESSAGES"):_.T("QUASAR_TIP_CONNECTED"):_.T("QUASAR_TIP_NOT_LOGIN");break;case 6:b=_.T("QUASAR_TIP_NOT_LOAD");break;default:b=_.T("QUASAR_TIP_DISCONNECTED")}a=a.e?"\n"+a.e:"";(b=_.T("CHROME_EXT_SHORT_NAME")+a+"\n"+b)&&window.chrome.browserAction.setTitle({title:b})};
_.gj.prototype.A=function(a,b,c){1!=this.a&&(a=b||_.T("QUASAR_MENUTEXT_UNKNOWN_USER"),a!=this.k&&(this.k=a),this.e=c)};_.gj.prototype.updateUserName=_.gj.prototype.A;_.gj.prototype.w=function(a,b){this.g!=b&&(this.g=b,fj(this),ij(this))};_.gj.prototype.setUnreadIndicator=_.gj.prototype.w;
var fj=function(a){window.chrome.browserAction.setIcon(jj(a,!0));window.chrome.systemIndicator&&window.chrome.systemIndicator.setIcon(jj(a))},kj=function(a){switch(a.a){case 2:return"offline_working";case 4:case 9:case 8:return a.c?a.g?"available_missed":"available":"offline";case 6:return"offline_unknown";default:return"offline"}},jj=function(a,b){var c=!b&&ri()?"_mac_":"_",d=kj(a),e=window.chrome.runtime.getURL("images_4/presence/"+d+c+"19.png"),c=window.chrome.runtime.getURL("images_4/presence/"+ d+c+"38.png");return{path:{19:e,38:c}}};_.gj.prototype.u=function(){var a=_.V.a();this.l.get(_.dj).a("qstcl");a.mb();a.b("onTrayClick",[1])};
var mj=function(a,b,c){_.J.call(this);this.a=b.createElement("IFRAME");b.body.appendChild(this.a);this.a.src=a;c&&(this.a.id=c,this.a.name=c);a=new _.I(this);_.G(this,a);_.Pd(_.Pd(a,this.a,"load",this.c),this.a,"error",lj).listen(b.defaultView,"focus",this.b).listen(b.body,"focus",this.b)};_.p(mj,_.J);mj.prototype.b=function(){_.bc(this.a.focus,this.a)};mj.prototype.c=function(){this.b()};mj.prototype.n=function(){this.a.parentElement.removeChild(this.a);this.a=null;mj.t.n.call(this)};
var nj={},oj=function(){delete nj.X},lj=function(){nj.X(1)};_.pj=function(a){this.c=a;this.a=new _.Xc;this.b=a.get(_.fi);this.a.setItem(new _.Tc("StartOnBrowserLaunch",!0,!1,!1));_.Yc&&this.a.setItem(new _.Tc("TopMost",!0));a=new _.Tc("StopOnBrowserClose",!1,!1,!1);a.setEnabled(!1);this.a.setItem(a);a=new _.Tc("TrayIcon",!0,!1,!1);a.setEnabled(null!=window.navigator.platform.match(/Win.*/)||si()||ri());this.a.setItem(a);(a=this.b.get("settings"))&&_.Wc(this.a,a);this.b.set("settings",_.Xh(this.a))};_.ga("ace.core.SettingsManager",_.pj);
var qj=window.chrome.runtime&&window.chrome.runtime.getURL&&window.chrome.runtime.getURL("settingsdialog.html")||"";_.pj.prototype.e=function(){this.b.set("settings",_.Xh(this.a));var a=_.V.e("setting");if(a&&0!=a.length)rj(a[0],"focus");else{var a=Math.floor((window.screen.height-200)/2),b=Math.floor((window.screen.width-520)/2),c=["width=520"];c.push("height=200");c.push("top="+a);c.push("left="+b);c.push("location=no");yi(qj,c.join(","))}};_.pj.prototype.launchSettingsDialog=_.pj.prototype.e;
_.pj.prototype.f=function(){var a=new _.Xc(_.Xh(this.a)),b=this.b.get("settings");_.Wc(this.a,b);var c=new _.Xc(b),b=c.getItem("StopOnBrowserClose"),a=a.getItem("TrayIcon"),c=c.getItem("TrayIcon");a.ba&&(c.G()||b.G()?(b=this.c.get(_.$h),ej(b),fj(b)):c.G()||b.G()||hj(this.c.get(_.$h)))};_.pj.prototype.updateSettingsFromStorage=_.pj.prototype.f;_.pj.prototype.j=function(){var a=_.V.e("setting");if(a)for(var b=0;b<a.length;++b)rj(a[b],"close")};_.pj.prototype.closeUI=_.pj.prototype.j; var rj=function(a,b){var c=new _.Oc;_.Rc(c,b);_.Sc(c,[]);_.V.b(a).sendMessage(c)};
var xj=function(a,b){_.I.call(this);this.b=a;_.Mc("viewer",""+(new Date).getTime());this.e=this.f=null;this.l=_.V;this.u=(0,_.m)();this.k=a.get(_.$h);var c=a.get(_.di),d=_.T("CHROME_EXT_SHORT_NAME"),e=zi("viewer-14.png"),f=zi("viewer-28.png"),d=sj(c,"viewer","viewer","viewer.html?viewer",d,e,f),e=b?_.P(b,_.tj,2).Ia():null,e=uj(c,new Gi(260,460),!0,e);vj(c,d.id,e);this.a=d;this.a.onClosed.addListener((0,_.q)(this.D,this));wj(this.a,(0,_.q)(this.p,this))};_.p(xj,_.I);
xj.prototype.n=function(){this.b.b(_.Bd)==this&&this.b.u();this.removeAll();xj.t.n.call(this)};var yj=function(a){_.F(a.f);a.f=null;_.F(a.e);a.e=null;_.Yh(a.c.a,"retryInfo").style.display="none"};xj.prototype.close=function(){_.F(this.a);this.b.b(_.Bd)==this&&this.b.u()};
xj.prototype.p=function(){this.c=new ti(zj(this.a).document);this.a.setTitle(_.T("CHROME_EXT_SHORT_NAME"));_.Yh(this.c.a,"retryMessage").textContent=_.T("CHROME_EXT_CANNOT_CONNECT");var a=_.Yh(this.c.a,"retryLink");a.textContent=_.T("QUASAR_TRY_NOW");this.listen(a,"click",this.q);this.listen(this.l,"onStatusChange",this.h);this.h()};xj.prototype.q=function(a){a.b();this.b.get(_.Zh).f()};
xj.prototype.h=function(){switch(this.k.a){case 3:if(!this.f){yj(this);var a;a=this.b.get(_.ei).a;a=new _.ie(a.b[0]);var b=new _.ie("/talkgadget/qsignin");_.R(b,"passive","1");_.R(b,"hl",window.chrome.i18n.getMessage("@@ui_locale"));a=_.me(a,b).toString();this.f=new mj(a,this.c.a)}break;case 2:yj(this);break;case 6:yj(this);_.Yh(this.c.a,"retryInfo").style.display="block";break;default:Aj(this)}}; var Aj=function(a){a.e||(yj(a),Bj(a.b.get(_.Zh)).then(function(a){this.e=new mj(a,this.c.a,"popoutRoster")},void 0,a))};
var Cj=function(a,b){this.b=_.Ud(a);this.a=0;this.c=b||!1};Cj.prototype.reset=function(){this.a=0};Cj.prototype.G=function(a){var b=this.b[this.a],b=(.5+1*Math.random())*b;a&&Dj(this);return b};var Dj=function(a){a.c&&a.a==a.b.length-1||a.a++};var Ej=function(a,b,c){_.E.call(this);this.b=a;this.e=b||0;this.c=c;this.X=(0,_.q)(this.f,this)};_.p(Ej,_.E);Ej.prototype.a=0;Ej.prototype.n=function(){Ej.t.n.call(this);this.stop();delete this.b;delete this.c};var Fj=function(a,b){a.stop();a.a=_.re(a.X,_.n(b)?b:a.e)};Ej.prototype.stop=function(){0!=this.a&&_.se(this.a);this.a=0};Ej.prototype.f=function(){this.a=0;this.b&&this.b.call(this.c)};
var Gj=function(a,b,c){_.E.call(this);this.c=a;this.b=b;this.a=c;this.X=(0,_.q)(this.Pc,this)};_.p(Gj,_.E);_.h=Gj.prototype;_.h.Oa=!1;_.h.na=null;_.h.stop=function(){this.na&&(_.se(this.na),this.na=null,this.Oa=!1)};_.h.n=function(){Gj.t.n.call(this);this.stop()};_.h.Pc=function(){this.na=null;this.Oa&&(this.Oa=!1,Hj(this))};var Hj=function(a){a.na=_.re(a.X,a.b);a.c.call(a.a)};
_.X=function(a){_.I.call(this);this.a=a;this.c=a.get(_.$h);this.S=a.b(_.di);this.L=_.uc();this.l=null;this.J=new Gj(this.f,6E4,this);_.G(this,this.J);a=(0,_.q)(this.ad,this);nj.X=a;_.kb(this,oj);this.h=!1;this.q=new Cj(Ci,!0);this.K=new Ej(this.od,this.q.G(),this);_.G(this,this.K);this.k=new Ej(this.lc,2E4,this);_.G(this,this.k);this.listen(window,"online",this.gd);this.w=this.A=0;this.b=new Cj(Di);this.e=new Ej(this.Aa,this.b.G(),this);_.G(this,this.e);window.chrome.cookies.onChanged.addListener((0,_.q)(this.Ba,
this));this.v=(0,_.q)(this.aa,this);this.u=(0,_.q)(this.W,this);window.chrome.tabs.onUpdated.addListener(this.v);window.chrome.tabs.onCreated.addListener(this.u)};_.p(_.X,_.I);_.ga("ace.core.DataChannelManager",_.X);_.X.prototype.n=function(){window.chrome.tabs.onCreated.removeListener(this.u);window.chrome.tabs.onUpdated.removeListener(this.v);delete this.u;delete this.v;_.F(this.l);_.X.t.n.call(this)};
_.X.prototype.p=function(a,b){_.Ij(this);a:{var c=this.a,d=c.b(_.Bd);if(d){if(Jj(d.a)?!Kj(d.a):1E3>(0,_.m)()-d.u){d.a.focus();break a}d.close()}d=new xj(c,b);c.a(_.Bd,d,!0)}};_.X.prototype.showViewer=_.X.prototype.p;_.X.prototype.Qa=function(a,b){this.L.a(b||"")};_.X.prototype.setRosterUrl=_.X.prototype.Qa;var Bj=function(a){return a.L.b};_.X.prototype.za=function(){this.c.f(0,1);var a=this.a.b(_.Bd);a&&a.close();Lj(this);this.h=!1};_.X.prototype.terminateApplication=_.X.prototype.za;
_.Ij=function(a){a.h||(a.listen(_.V,"onStatusChange",a.Ec),a.f(),a.a.get(_.ei),a.h=!0)};_.X.prototype.f=function(){this.C||(this.c.f(0,2),Lj(this),this.l=new mj(window.chrome.runtime.getURL("datachannel.html"),window.document,"centralRoster"))};var Lj=function(a){a.S.f();a.a.get(_.ci).b();_.F(a.l);a.l=null;a.L=_.uc()},Nj=function(a,b){var c=hi(a.a.get(_.ei).a);window.chrome.cookies.getAll({url:c},(0,_.q)(function(a){a=a&&Mj("SID",a)&&Mj("SSID",a)&&Mj("SAPISID",a);b(a)},a))};
_.X.prototype.Ca=function(a){var b=this.c.a;if(a){if(3==b){if(a=0==this.e.a)a=this.b,a=a.a<a.b.length;a&&Fj(this.e,this.b.G())}}else 3!=b&&this.f()};_.X.prototype.Ba=function(a){"SSID"!=a.cookie.name&&"SAPISID"!=a.cookie.name||".google.com"!=a.cookie.domain||Nj(this,(0,_.q)(this.Ca,this))};var Mj=function(a,b){return(0,_.za)(b,function(b){var d=b.expirationDate&&b.expirationDate<(0,_.m)()/1E3;return b.name==a&&".google.com"==b.domain&&!d})};_.h=_.X.prototype;
_.h.Ec=function(){this.K.stop();this.k.stop();switch(this.c.a){case 2:Fj(this.k);break;case 6:Fj(this.K,this.q.G());break;case 4:case 9:case 8:case 5:this.q.reset(),this.e.stop()}};_.h.gd=function(){if(4!=this.c.a){var a=this.J;a.na?a.Oa=!0:Hj(a)}};_.h.od=function(){Dj(this.q);this.f()};_.h.ad=function(a){Lj(this);switch(a){case 1:this.lc();break;case 2:a=this.J,a.na?a.Oa=!0:Hj(a)}};_.h.lc=function(){this.C||(this.k.stop(),this.c.f(0,6))};
var Oj=function(a){a.w++;var b=a.a.get(_.dj);1==a.w?b.a("qccro"):2==a.w?b.a("qccrt"):b.a("qccrm")};_.X.prototype.Aa=function(){Dj(this.b);Oj(this);Nj(this,(0,_.q)(function(a){a&&this.f()},this))};_.X.prototype.aa=function(a,b){b.url&&Pj(this,b.url)};_.X.prototype.W=function(a){a.url&&Pj(this,a.url)}; var Qj=function(a){a.A++;var b=a.a.get(_.dj);1==a.A?b.a("qctro"):2==a.A?b.a("qctrt"):b.a("qctrm")},Pj=function(a,b){(0,_.za)(Bi,function(a){return a.test(b)})&&0!=a.b.a&&(a.b.reset(),Qj(a),0!=a.e.a&&Fj(a.e,a.b.G()))};
var Rj=function(a,b){this.a=a;this.h=b;this.k=window.chrome.runtime.getURL("images_4/icon-128x128.png");this.j=this.g=this.l="";this.e=0;this.b=[];this.f=""},Sj=function(a){this.name=a;this.title=""};Rj.prototype.setTitle=function(a){a&&(this.l=a)};
var Tj=function(a){return a.replace(/^(\<br\>)+/,"")},Uj=function(a){var b=a.l;a.g&&(b+=" "+a.g);var c=Tj(a.j||7!=a.h?a.j||"":_.T("CHROME_EXT_ONEONONE_PLUS_HANGOUT_DETAILS")),d=(0,_.xa)(a.b,function(a){var b;if(!(b=a.title))a:{switch(a.name){case "join hangout":b=_.T("QUASAR_ANSWER_BUTTON_TEXT");break a;case "ignore":b=_.T("QUASAR_DECLINE_BUTTON_TEXT");break a}b=""}return{title:b}},a);return{type:"basic",iconUrl:a.k,title:b,message:c,buttons:d,priority:2}};
var Vj=function(){this.b=new _.B;this.a=new _.Ei(18E5);_.Hb(this.a,"tick",(0,_.q)(this.c,this,this.b,0,200));_.Fi(this.a)};_.p(Vj,_.E);Vj.prototype.n=function(){this.a.D()};var Wj=function(a,b){var c=null!=b.c?b.a+b.c:null;return null!=c?_.Ua(a.b,c):!1};Vj.prototype.add=function(a){var b=null!=a.c?a.a+a.c:null;null!=b&&!Wj(this,a)&&this.b.set(b,(0,_.m)()+18E5)};
Vj.prototype.c=function(a,b,c){var d=a.V();if(0!=d){var e=0;null!=b&&0<b&&(e=b<d?b:d);b=d;null!=c&&c<d&&(b=0<c?c:0);e>b&&(e=b);var f=[];c=a.ha(!0);Ji(c,function(b){f.push([b,a.get(b)])});f.sort(function(a,b){return a[1]-b[1]});if(31536E7<f[d-1][1]-f[0][1])a.clear();else{c=0;b=d-b;for(var d=d-e,e=(0,_.m)(),g=0;g<f.length;++g)if(c<b||c<d&&f[g][1]<=e)a.remove(f[g][0]),c+=1;else break}}};
var Xj=function(a){_.x(this,a,"acr:bcr",null)};_.p(Xj,_.w);_.z("acr:bcr",Xj);var Yj=function(a){_.x(this,a,"acr:srs",null)};_.p(Yj,_.w);_.z("acr:srs",Yj);var Zj=function(a){_.x(this,a,"acr:rss",null)};_.p(Zj,_.w);_.z("acr:rss",Zj);var ak=function(a){_.x(this,a,"acr:rrs",null)};_.p(ak,_.w);_.z("acr:rrs",ak);var bk=function(a){_.x(this,a,"acr:rsr",null)};_.p(bk,_.w);_.z("acr:rsr",bk);_.dk=function(a){_.x(this,a,"acr:wrs",ck)};_.p(_.dk,_.w);var ck=[1];_.z("acr:wrs",_.dk); var ek=function(a){_.x(this,a,0,null)};_.p(ek,_.w);ek.prototype.Z=function(){return _.y(this,2)};ek.prototype.Ha=function(){return _.y(this,11)};
var ik;_.gk=function(a){_.x(this,a,"acq:rs",fk)};_.p(_.gk,_.w);var fk=[3];_.z("acq:rs",_.gk);var hk=function(a){_.x(this,a,0,null)};_.p(hk,_.w);hk.prototype.getState=function(){return _.y(this,6)};_.tj=function(a){_.x(this,a,0,null)};_.p(_.tj,_.w);_.tj.prototype.Ia=function(){return _.P(this,hk,1)};ik=function(a,b){_.Qd(a,1,b)};_.jk=function(a){_.x(this,a,0,null)};_.p(_.jk,_.w);_.jk.prototype.Z=function(){return _.y(this,1)};var kk=function(a,b){_.M(a,1,b)}; _.jk.prototype.Ia=function(){return _.P(this,hk,2)};var lk=function(a,b){_.Qd(a,2,b)};_.jk.prototype.Ha=function(){return _.y(this,3)};var mk=function(a,b){_.M(a,3,b)};
var nk,rk,qk;nk=function(a){this.c=a;this.a={};this.b=a.get(_.fi)};_.ok=function(a,b){return(null!=a?a:"null")+"-"+(null!=b?b:"null")};
rk=function(a,b){_.re(a.reload,6E4,a);var c=[],d={},e=a.c.get(_.di),f=_.Li(b,ek,1)||[];(0,_.v)(f,function(a){c.push(_.y(a,1));var b=_.ok(a.Z(),a.Ha());d[b]=a});var g=c.length;c.push("viewer");pk(e,c,(0,_.q)(function(a){for(var c=[],e=0;e<f.length;e++){var N=a[e];if(N){var fa=f[e],Q=new _.jk;mk(Q,fa.Ha());kk(Q,fa.Z());lk(Q,qk(N));c.push(Q)}}_.Mi(c,function(a,b){var c=b.Ia(),c=_.y(c,2),d;d=a.Ia();d=_.y(d,2);return c-d});(0,_.v)(c,function(a,b){var c=_.ok(a.Z(),a.Ha());_.M(d[c],3,b)});a=a[g];e=new _.gk;
a&&(N=new _.tj,ik(N,qk(a)),_.Qd(e,2,N));_.Ki(e,3,c);_.Ki(b,1,f);_.Qd(e,1,b);this.b.set("ReloadState",e.F);_.V.a().b("eventReloadStateSaved",[])},a))};qk=function(a){var b=new hk;_.M(b,1,a.top);_.M(b,2,a.left);_.M(b,3,a.width);_.M(b,4,a.height);_.M(b,5,a.focused);_.M(b,6,a.state);_.M(b,7,a.alwaysOnTop);return b};nk.prototype.read=function(){var a=this.j;this.j=null;_.V.a().b("eventReloadStateRead",[a&&a.F||null])};nk.prototype.reload=function(){window.chrome.runtime.reload()};
_.Y=function(a){this.a=new nk(a);this.b=a;window.chrome.runtime.onUpdateAvailable.addListener((0,_.q)(this.g,this))};_.ga("ace.core.ExtensionLibrary",_.Y);_.Y.prototype.g=function(){_.V.a().b("eventReloadClient",[]);_.re(this.a.reload,864E5+288E5*Math.random(),this.a)};_.Y.prototype.q=function(a,b,c,d){a=_.V.b(b);null!=a&&_.n(d)&&d&&(d=a.h,null!=d&&null!=d.id&&(window.chrome.tabs.update(d.id,{selected:!0}),c&&window.chrome.tabs.get(d.id,function(a){_.mi(a.windowId)})))};_.Y.prototype.selectTab=_.Y.prototype.q;
_.Y.prototype.h=function(a,b,c){c?yi(b,"width=500,height=400"):window.chrome.tabs.create({url:b,selected:!0},function(a){null!=a?_.re(function(){window.chrome.tabs.get(a.id,function(a){_.mi(a.windowId)})},2E3):yi(b)})};_.Y.prototype.openUrl=_.Y.prototype.h;_.Y.prototype.f=function(a,b){this.c=this.b.get(_.di);this.c.focus(b)};_.Y.prototype.focusMoleByFrameId=_.Y.prototype.f;_.Y.prototype.e=function(){_.V.a().mb()};_.Y.prototype.showApplication=_.Y.prototype.e;
_.Y.prototype.p=function(a,b){var c=new _.dk(b);rk(this.a,c)};_.Y.prototype.saveReloadState=_.Y.prototype.p;_.Y.prototype.k=function(){this.a.read()};_.Y.prototype.readReloadState=_.Y.prototype.k;_.Y.prototype.l=function(){this.a.reload()};_.Y.prototype.reloadExtension=_.Y.prototype.l;_.Y.prototype.j=function(){_.V.a().Cc()};_.Y.prototype.onHostReady=_.Y.prototype.j;
var sk=function(a,b){if(a)this.focused=a.focused,this.alwaysOnTop=a.alwaysOnTop,this.top=a.top,this.left=a.left,this.width=a.width,this.height=a.height,this.state=a.state;else if(b){this.focused=b.contentWindow.document.hasFocus();this.alwaysOnTop=b.isAlwaysOnTop();var c=b.getBounds();this.top=c.top;this.left=c.left;this.width=c.width;this.height=c.height;this.state=b.isMinimized()?"minimized":"normal"}else this.alwaysOnTop=this.focused=!1,this.height=this.width=this.left=this.top=0,this.state=""}; sk.prototype.isMinimized=function(){return"minimized"==this.state};
var tk=function(a,b,c){this.a=c||new sk;c||(this.a.alwaysOnTop=ii(a.get(_.ei).a))};tk.prototype.getProperties=function(){return this.a};var vk=function(a,b,c){(b=b.f)?uk(a.get(_.di),b,function(b){c(new tk(a,0,b))}):c(new tk(a))};var wk=function(){_.E.call(this);this.a=new _.Ii};_.p(wk,_.E);wk.prototype.da=function(a){var b,c=Array.prototype.slice.call(arguments);(0,_.v)(this.a.B(),function(a){b=a.apply(null,c)});return b};wk.prototype.addListener=function(a){this.a.add(a)};wk.prototype.removeListener=function(a){this.a.remove(a)};wk.prototype.n=function(){this.a.clear();wk.t.n.call(this)};
var zk=function(){_.E.call(this);this.b=[];this.h=new wk;_.G(this,this.h);this.f=new wk;_.G(this,this.f);this.onClosed=new wk;this.g=!1;this.c=null;this.k=(0,_.q)(this.A,this);xk.addListener(this.k);this.l=(0,_.q)(this.w,this);yk.addListener(this.l)};_.p(zk,_.E);zk.prototype.n=function(){Kj(this)||void 0!=this.a&&window.chrome.windows.remove(this.a);Ak(this);this.k&&(xk.removeListener(this.k),yk.removeListener(this.l));_.F(this.onClosed);zk.t.n.call(this)};
var xk=window.chrome.windows&&window.chrome.windows.onRemoved,yk=window.chrome.windows&&window.chrome.windows.onFocusChanged;zk.prototype.create=function(a){window.chrome.windows.create(a,(0,_.q)(function(a){this.C?window.chrome.windows.remove(a.id):(this.a=a.id,Bk(this))},this))};
var Bk=function(a){if(null!=a.b&&Jj(a))if(Kj(a))Ak(a);else{for(;a.b.length&&!Kj(a);)a.b.shift()(a);a.b=null}},Jj=function(a){return!(!_.ka(a.a)||!a.e)},wj=function(a,b){Kj(a)?Ak(a):null==a.b?b(a):a.b.push(b)},Kj=function(a){return!(!a.e||!a.e.closed)};zk.prototype.A=function(){Kj(this)&&Ak(this)};var Ak=function(a){if(!a.g){var b=a.onClosed;a.onClosed=new wk;_.re((0,_.q)(function(){this.g||(this.g=!0,b.da(this));_.F(b)},a))}};
zk.prototype.w=function(a){if(a!=this.a){if(null===this.c||this.c)this.c&&(this.c=!1),this.f.da(this)}else this.c=!0,this.h.da(this)};var zj=function(a){var b;b=a.a?a.e:null;return!b||Kj(a)?null:b};zk.prototype.isMinimized=function(){return this.u.isMinimized()};zk.prototype.isMaximized=function(){return this.u.isMaximized()};zk.prototype.minimize=function(){wj(this,(0,_.q)(function(){window.chrome.windows.update(this.a,{state:"minimized"})},this))};
zk.prototype.focus=function(){wj(this,(0,_.q)(function(){window.chrome.windows.update(this.a,{focused:!0})},this))};var Ck=function(a,b){wj(a,(0,_.q)(function(){window.chrome.windows.update(this.a,{drawAttention:b})},a))};zk.prototype.getProperties=function(a){wj(this,_.ha(Dk,[this],function(b){a(b[0])}))}; var Dk=function(a,b){window.chrome.windows.getAll(function(c){var d={};(0,_.v)(c,function(a){d[a.id]=a});var e=[];(0,_.v)(a,function(a){var b;a&&Jj(a)&&!Kj(a)&&(b=d[a.a]);var c;b&&(c=new sk(b));e.push(c)});b(e)})};
var Ek=function(){zk.call(this)};_.p(Ek,zk);Ek.prototype.setTitle=function(a){wj(this,(0,_.q)(function(){zj(this).document.title=a},this))};
var Gk=function(a,b){a.q=b;wj(a,(0,_.q)(function(){Fk(this)},a))},Hk=function(a,b){a.v=b;wj(a,(0,_.q)(function(){Fk(this)},a))},Fk=function(a){var b=zj(a).document,c=b.querySelector("HEAD"),d=c.querySelectorAll("link[rel='shortcut icon']"),e=zi("icon-24x24.png");a=[a.q||e,a.v];for(var e=_.Nc()?2:1,f="",g=0;g<e;++g)if(a[g]&&a!=f){var f=a[g],l=d[g];l||(l=b.createElement("LINK"),c.appendChild(l));l.rel="shortcut icon";var r=a[g];l.type=qi(r,".ico")?"image/x-icon":qi(r,".gif")?"image/gif":"image/png"; l.href=a[g]}};
var Kk,Ik,Lk;_.Jk=function(a){this.a={};if(a)for(var b=0;b<a.length;b++)this.a[Ik(a[b])]=null;for(var c in Object.prototype);};Kk={};Ik=function(a){return a in Kk||32==String(a).charCodeAt(0)?" "+a:a};Lk=function(a){return 32==a.charCodeAt(0)?a.substr(1):a};_.h=_.Jk.prototype;_.h.add=function(a){this.a[Ik(a)]=null};_.h.clear=function(){this.a={}};_.h.clone=function(){var a=new _.Jk,b;for(b in this.a)a.a[b]=null;return a};_.h.contains=function(a){return Ik(a)in this.a};
_.h.forEach=function(a,b){for(var c in this.a)a.call(b,Lk(c),void 0,this)};_.h.V=Object.keys?function(){return Object.keys(this.a).length}:function(){var a=0,b;for(b in this.a)a++;return a};_.h.B=Object.keys?function(){return Object.keys(this.a).map(Lk,this)}:function(){var a=[],b;for(b in this.a)a.push(Lk(b));return a};_.h.P=function(){for(var a in this.a)return!1;return!0};_.h.remove=function(a){a=Ik(a);return a in this.a?(delete this.a[a],!0):!1};_.h.ha=function(){return wi(this.B())};
_.Z=function(a){_.E.call(this);this.h=a;this.a={};this.c={};this.b=new _.Jk;_.ga("__onPanelLoad",(0,_.q)(this.I,this));this.p=a.get(_.$h);a=new _.I(this);_.G(this,a);a.listen(_.V,"onStatusChange",this.u)};_.p(_.Z,_.E);_.ga("ace.core.PanelsManager",_.Z);_.Z.prototype.n=function(){for(var a in this.a)this.fb(this.a[a]);_.Z.t.n.call(this)};
_.Z.prototype.isMaximized=function(a,b){var c=function(a){a=a?!a.isMinimized():null;_.V.a().b("eventIsMinimizedResponse",[b,a])},d=this.a[b];d?d.getProperties(c):c(void 0)};_.Z.prototype.isMaximized=_.Z.prototype.isMaximized;
_.Z.prototype.J=function(a,b,c,d,e,f,g,l,r,C){a="panel.html?"+b;d=d||_.T("CHROME_EXT_SHORT_NAME");b=sj(this,b,l||b,a,d,e,g);wj(b,(0,_.q)(this.k,this,c));c=new Gi(280,420);r||C?(r=r||null,e=C||null,C=this.h.get(_.ai).a,r=_.ok(r,e),(e=C.a[r])&&delete C.a[r],C=e?e.Ia():null):C=null;f=uj(this,c,!!f,C);vj(this,b.id,f)};_.Z.prototype.openPanel=_.Z.prototype.J;
_.Z.prototype.v=function(a,b,c,d,e,f,g){a="dialog.html?"+b;d=d||_.T("CHROME_EXT_SHORT_NAME");b=sj(this,b,b,a,d);wj(b,(0,_.q)(this.k,this,c));c=uj(this,new Gi(f,g),e,null);c.Uc=!0;vj(this,b.id,c);return b};_.Z.prototype.openDialog=_.Z.prototype.v;var sj=function(a,b,c,d,e,f,g){a.a[b]&&a.fb(a.a[b]);var l=new Ek;l.id=b;l.key=c;l.url=d;l.setTitle(e);Gk(l,f);Hk(l,g);a.a[b]=l;a.c[c]=b;return l};_.Z.prototype.k=function(a,b){b.p=new mj(a,zj(b).document);_.G(b,b.p)};
var uj=function(a,b,c,d){b={focus:c,ya:null,width:b.width,height:b.height,minimize:!1};if(d){b.top=_.y(d,1);b.left=_.y(d,2);c=_.y(d,3);var e=_.y(d,4);_.y(d,7)?(b.width=Math.max(b.width,c),b.height=Math.max(b.height,e)):(b.width=c,b.height=e);"minimized"==d.getState()&&(b.minimize=!0);b.ya=_.y(d,7);b.focus=_.y(d,5)}b.ya="boolean"==typeof b.ya?b.ya:ii(a.h.get(_.ei).a);return b},vj=function(a,b,c){var d=a.a[b];d.onClosed.addListener((0,_.q)(a.fb,a));d.h.addListener((0,_.q)(a.A,a));d.f.addListener((0,_.q)(a.w,
a));c.minimize&&d.minimize();b="panel";c.ya||(b=si()?"popup":"detached_panel");c.Uc&&(b="popup");var e={type:b,url:d.url,focused:c.focus,width:c.width,height:c.height};if(b=null!=c.top&&null!=c.left)e.top=c.top,e.left=c.left;b||c.ya?d.create(e):pk(a,Object.keys(a.c),(0,_.q)(function(a){var b=window.screen,c;c=new Gi(260,460);var r=new Gi(280,420);c=new Gi(Math.max(c.width,r.width),Math.max(c.height,r.height));for(var C=b.availWidth,N=b.availHeight-50,r=b.availTop+N%c.height,b=b.availLeft+C%c.width,
C=Math.floor(C/c.width),fa=Math.floor(N/c.height),N=Array(C*fa),Q=0;Q<a.length;Q++){var na=a[Q];if(na){for(var Mb=[na.left,na.left+na.width-1],na=[na.top,na.top+na.height-1],pa=0;2>pa;pa++)Mb[pa]=Math.floor(Math.max(0,Mb[pa]-b)/c.width),na[pa]=Math.floor(Math.max(0,na[pa]-r)/c.height);for(pa=Mb[0];pa<=Mb[1];pa++)for(var eb=na[0];eb<=na[1];eb++)pa<C&&eb<fa&&(N[pa+eb*C]=1)}}a=N.length-1;for(Q=N.length-1;0<=Q;Q--)if(!N[Q]){a=Q;break}N=a%C*c.width;e.top=r+Math.floor(a/C)*c.height+(c.height-e.height);
e.left=b+N+(c.width-e.width);d.create(e)},a))};_.Z.prototype.g=function(a,b){var c=this.a[b];c&&_.F(c)};_.Z.prototype.closePanel=_.Z.prototype.g;_.Z.prototype.f=function(){for(var a in this.a)0==this.a[a].url.indexOf("panel.html")&&this.g(0,a)};_.Z.prototype.closeAllPanels=_.Z.prototype.f;_.Z.prototype.setTitle=function(a,b,c){(a=this.a[b])&&a.setTitle(c)};_.Z.prototype.setTitle=_.Z.prototype.setTitle;_.Z.prototype.q=function(a,b,c){this.a[b]&&Ck(this.a[b],c)};_.Z.prototype.drawAttention=_.Z.prototype.q;
_.Z.prototype.focus=function(a){if(this.a[a]){var b=this.a[a];b.getProperties((0,_.q)(function(a){if(a&&(a=zj(b),0==a.outerWidth&&0==a.outerHeight)){this.fb(b);return}b.focus()},this))}};_.Z.prototype.L=function(a,b,c){this.a[b]&&Gk(this.a[b],c)};_.Z.prototype.setPresence=_.Z.prototype.L;_.Z.prototype.K=function(a,b,c){this.a[b]&&Hk(this.a[b],c)};_.Z.prototype.setAvatar=_.Z.prototype.K;_.Z.prototype.e=function(a,b,c){for(var d in this.a)(b||this.b.contains(d))&&this.l(0,d,b,c);b||this.b.clear()};
_.Z.prototype.minimizeAllPanelsIfTopmost=_.Z.prototype.e;_.Z.prototype.l=function(a,b,c,d){var e=this.a[b];e&&e.getProperties((0,_.q)(function(a){if(a&&a.alwaysOnTop&&!this.C)if(c){var g;(g=!d)||(g=new _.Ai(a.left,a.top,a.width,a.height),g=g.left<=d.left+d.width&&d.left<=g.left+g.width&&g.top<=d.top+d.height&&d.top<=g.top+g.height);g&&!a.isMinimized()&&(e.minimize(),this.b.add(b))}else window.chrome.windows.update(e.a,{state:"normal"}),this.b.remove(b)},this))};
_.Z.prototype.minimizePanelIfTopmost=_.Z.prototype.l;_.Z.prototype.I=function(a){var b=this.a[a.location.search.substring(1)];b&&(b.e=a,Bk(b))};var uk=function(a,b,c){a=a.a[a.c[b]];!a||Kj(a)?c(void 0):a.getProperties(c)},pk=function(a,b,c){var d=[];(0,_.v)(b,(0,_.q)(function(a){d.push(this.a[this.c[a]])},a));Dk(d,c)};_.Z.prototype.fb=function(a){this.a[a.id]==a&&(this.b.remove(a.id),delete this.c[a.key],delete this.a[a.id],_.F(a))};_.Z.prototype.A=function(a){this.a[a.id]==a&&this.b.remove(a.id)}; _.Z.prototype.w=function(a){this.a[a.id]==a&&_.V.a().b("eventBlurred",[a.id])};_.Z.prototype.u=function(){3==this.p.a&&this.f()};
_.Mk=function(a){_.E.call(this);this.k=a;this.a=new _.B;this.h=new _.B;this.c=new Vj;_.G(this,this.c);this.g=(0,_.q)(this.Xc,this);window.chrome.notifications.onClosed.addListener(this.g);this.e=(0,_.q)(this.Fc,this);window.chrome.notifications.onClicked.addListener(this.e);this.f=(0,_.q)(this.Wc,this);window.chrome.notifications.onButtonClicked.addListener(this.f)};_.p(_.Mk,_.E);_.ga("ace.core.NotificationManager",_.Mk);
_.Mk.prototype.n=function(){_.v(this.a.B(),_.F);this.a.clear();window.chrome.notifications.onClosed.removeListener(this.g);window.chrome.notifications.onClicked.removeListener(this.e);window.chrome.notifications.onButtonClicked.removeListener(this.f);_.Mk.t.n.call(this)};
_.Mk.prototype.p=function(a,b){var c;if(b&&b.Content){c=[b.Id.ServiceUrl,b.Id.ServiceId].join(";");0==c.indexOf("bc")?c=new Rj(c,2):0==c.indexOf("hangout")?(c=new Rj(c,7),c.b.push(new Sj("join hangout")),c.b.push(new Sj("ignore"))):c=void 0;c.setTitle(b.Content.TitleText);c.g=b.Content.SubtitleText;c.j=b.Content.BodyText;c.c=b.Content.BodyTextId;var d=0;b.Content.EndTimeMs&&(d=b.Content.EndTimeMs,(0,window.isNaN)(d)||!(0,window.isFinite)(d))&&(d=0);d=d||(0,_.m)()+1E4;c.e=d;if(b.Content.ServiceIcon){var d=
c,e=b.Content.ServiceIcon;e&&(0==e.indexOf("images_4/")&&(e=window.chrome.runtime.getURL(e)),d.k=e)}b.Content.FrameId&&(c.f=b.Content.FrameId)}else c=null;c&&(_.V.a().b("eventLogImpression",["qnop"]),Wj(this.c,c)||(this.c.add(c),Nk(this,c)))};_.Mk.prototype.registerNotification=_.Mk.prototype.p;
var Nk=function(a,b){2==b.h||b.f?vk(a.k,b,function(c){c=c.getProperties();c.focused||c.alwaysOnTop||Ok(a,b)}):Ok(a,b)},Ok=function(a,b){var c=b.a,d=b.e-(0,_.m)();0>=d?a.ac(c):(a.a.set(c,b),window.chrome.notifications.create(c,Uj(b),function(){_.V.a().b("eventLogImpression",["qtod"])}),_.se(a.h.get(c,null)),b.e!=Number.MAX_VALUE&&a.h.set(c,_.re((0,_.q)(a.ac,a,c),d)),_.V.a().b("eventLogImpression",["qnst"]))};_.Mk.prototype.b=function(){(0,_.v)((0,_.wa)(this.a.B(),ji),this.Ea,this)};
_.Mk.prototype.cleanAllNotifications=_.Mk.prototype.b;_.Mk.prototype.l=function(a,b){var c=this.a.get(b);c&&this.Ea(c)};_.Mk.prototype.cleanANotification=_.Mk.prototype.l;_.h=_.Mk.prototype;_.h.Ea=function(a){a=a.a;window.chrome.notifications.clear(a,_.oa);this.a.remove(a)};_.h.Xc=function(a,b){b&&this.a.get(a)&&(this.a.remove(a),Pk(a,"toastEventOnClose"))};_.h.Fc=function(a){var b=this.a.get(a);b&&(Pk(a,"toastEventOnBody"),this.Ea(b))};
_.h.Wc=function(a,b){var c=this.a.get(a);c&&(Pk(a,"toastEventOnButton",c.b[b].name),this.Ea(c))};_.h.ac=function(a){var b=this.a.get(a);b&&(Pk(a,"toastEventOnTimeout"),this.Ea(b))};var Pk=function(a,b,c){var d=_.V;(d=d&&d.a())&&!d.C&&_.V.a().b(b,[a,c,"",!1])};
_.Qk=function(a){_.x(this,a,"f.mt",null)};_.p(_.Qk,_.w);_.z("f.mt",_.Qk);_.Rk=function(a){_.x(this,a,"er",null)};_.p(_.Rk,_.w);_.z("er",_.Rk);_.Rk.prototype.Ua=function(){return _.y(this,9)};_.Rk.prototype.getData=function(){return _.y(this,4)};new _.Ii;_.D&&_.gb(8);var Sk=function(){throw Error("y");};Sk.prototype.a=null;Sk.prototype.toString=function(){return this.content};var Tk=function(){Sk.call(this)};_.p(Tk,Sk);(function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){var e=new b(String(a));void 0!==d&&(e.a=d);return e}})(Tk);(function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){var e=String(a);if(!e)return"";e=new b(e);void 0!==d&&(e.a=d);return e}})(Tk);
var Uk=function(a,b){_.bd.call(this,a,b)};_.p(Uk,_.bd);_.Vk=function(a){a?(this.a=_.y(a,1)||-1,_.y(a,2),_.y(a,3),_.y(a,4),_.y(a,13)):this.a=-1};_.Wk=new _.Vk;_.Xk=function(){};_.p(_.Xk,_.we);_.Xk.prototype.b=function(){};_.Xk.prototype.b.gc=!0;_.Xk.t||_.p(_.Xk,_.we);_.U.a={};_.U.a.kb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";_.U.a.ib=_.U.a.kb+"0123456789";_.U.a.lb=_.U.a.kb.length;_.U.a.jb=_.U.a.ib.length;_.U.a.Fb=-2147483648;_.U.a.pd=function(a){for(var b=0,c=a.length-1;0<=c;c--)b=b*(0==c?_.U.a.lb:_.U.a.jb)+_.U.a.ib.indexOf(a.charAt(c));return b+_.U.a.Fb};_.U.a.toString=function(a){var b=[],c=0;a-=_.U.a.Fb;b[c++]=_.U.a.kb.charAt(a%_.U.a.lb);for(a=Math.floor(a/_.U.a.lb);0<a;)b[c++]=_.U.a.ib.charAt(a%_.U.a.jb),a=Math.floor(a/_.U.a.jb);return b.join("")};
new Uk(_.dd,"f_req");
}catch(e){_._DumpException(e)}
try{
var Mn=function(a,b,c){a.timeOfStartCall=(new Date).getTime();if(b&&JSON&&JSON.stringify){var d=JSON.stringify(b);200>=d.length&&(a.psdJson=d)}d=c||_.k;d.GOOGLE_FEEDBACK_START_ARGUMENTS=arguments;var e=a.serverUri||"//www.google.com/tools/feedback",f=d.GOOGLE_FEEDBACK_START;if(f)f.apply(d,arguments);else{var e=e+"/load.js?",g;for(g in a)f=a[g],null!=f&&!_.ia(f)&&(e+=(0,window.encodeURIComponent)(g)+"="+(0,window.encodeURIComponent)(f)+"&");g=d.document;d=g.createElement("script");d.src=e;g.body.appendChild(d)}}; _.ga("userfeedback.api.startFeedback",Mn);
var Nn=function(){_.I.call(this);this.listen(window,"unload",this.D);window.document.title=_.T("CHROME_EXT_SHORT_NAME")+": "+_.T("CHROME_EXT_FEEDBACK_SUBTITLE");_.S("system-legend").innerText=_.T("QUASAR_FEEDBACK_SYSTEM_LEGEND");_.S("system-platform-label").innerText=_.T("QUASAR_FEEDBACK_PLATFORM_LABEL");_.S("system-platform-value").innerText=window.navigator.platform;_.S("system-user-agent-label").innerText=_.T("QUASAR_FEEDBACK_USER_AGENT_LABEL");_.S("system-user-agent-value").innerText=window.navigator.userAgent;
_.S("user-legend").innerText=_.T("CHROME_EXT_FEEDBACK_COMMENTS");_.S("privacy-legend").innerText=_.T("QUASAR_FEEDBACK_PRIVACY_LEGEND");_.S("privacy-text").innerText=_.T("QUASAR_FEEDBACK_PRIVACY_TEXT");var a=_.S("submit-button");a.innerText=_.T("QUASAR_FEEDBACK_SUBMIT_BUTTON");this.listen(a,"click",this.b);a=_.S("cancel-button");a.innerText=_.T("QUASAR_FEEDBACK_CANCEL_BUTTON");this.listen(a,"click",this.a);_.S("user-text-value").focus()};_.p(Nn,_.I);
Nn.prototype.b=function(){var a=_.S("user-text-value").value;if(a&&(a=a.trim())){var a={flow:"submit",serverUri:_.T("QUASAR_FEEDBACK_SERVER_URI"),productId:83052,locale:window.chrome.i18n.getMessage("@@ui_locale"),report:{description:a},callback:this.a},b={version:window.chrome.runtime.getManifest().version,build:window.chrome.runtime.id};_.S("submit-button").disabled=!0;Mn(a,b)}};Nn.prototype.a=function(){window.close()};window.addEventListener("load",function(){new Nn},!1);

}catch(e){_._DumpException(e)}
}).call(this,this.default_feedback);
// Google Inc.
