name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Dependencies 📦
        run: npm ci

      - name: Build Project 🏗️
        run: npm run build
        env:
          PUBLIC_URL: 'craigiswayne.com'

      - name: Build CV
        run: node resume-generator/compile.js

      - name: List files
        run: ls -laGh ./build

      - name: Generate Resume PDF
        run: node resume-generator/create_pdf_from_html.js


      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Automated deployment to GitHub Pages'
          cname: 'craigiswayne.com'

  tests:
    needs: build-and-deploy

    name: 'Tests'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5

      - name: 'API requests'
        id: 'http-client'
        uses: madhead/intellij-http-client-action@latest
        with:
          files: |-
            ./tests/important-files.http
            ./tests/site-response.http
          report: true

      - name: 'Publish Test Results'
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            reports/**/*.xml

  tests-cypress:
    name: Tests 🧪
    needs: build-and-deploy
    uses: craigiswayne/ci-cd/.github/workflows/_npm-install-build-lint-test.yml@v0.0.10
    with:
      run_build: false
      run_lint: false
      test_command: 'cy:run'

