name: PR Checks

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18.x, 19.x, 20.x, 21.x, 22.x, 23.x, 24.x ]
    permissions:
      contents: write

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies 📦
        run: npm ci

      - name: Build Project 🏗️
        run: npm run build
        env:
          PUBLIC_URL: 'craigiswayne.com'