# see https://make.wordpress.org/cli/handbook/config/

color: true

core config:
    dbuser: wordpress
    dbpass: wordpress
    extra-php: |
        define( 'WP_DEBUG', true );
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_POST_REVISIONS', 50 );
