# See here for more info: https://make.wordpress.org/cli/handbook/config/
color: true

core config:
    dbuser: root
    dbpass: root

config create:
    dbuser: root
    dbpass: root

@dev-old:
    ssh: root@152.111.240.157
    path: /var/www

@dev:
    ssh: root@152.111.240.159
    path: /var/www
