# See here for more info: https://make.wordpress.org/cli/handbook/config/

user: craigiswayne

color: true

core config:
    dbuser: wordpress
    dbpass: wordpress

config create:
    dbuser: wordpress
    dbpass: wordpress

@dev-old:
    ssh: root@152.111.240.157
    path: /var/www

@dev:
    ssh: root@152.111.240.159
    path: /var/www
